-- =====================================================
-- EquipQR Seed Data - Excavator PM Template (Global)
-- =====================================================
-- This seed creates the global Excavator PM checklist template.
-- Global templates have organization_id = NULL and is_protected = true.
--
-- Template: Excavator PM
-- Items: 84 checklist items across 12 sections
-- =====================================================

INSERT INTO "public"."pm_checklist_templates" (
  "id",
  "organization_id",
  "name",
  "description",
  "template_data",
  "is_protected",
  "created_by",
  "created_at",
  "updated_at"
)
SELECT
  'cc0e8400-e29b-41d4-a716-446655440005'::uuid,
  NULL,
  'Excavator PM',
  'Comprehensive preventative maintenance checklist for excavators. Covers visual inspection, engine compartment, electrical system, hydraulic system, undercarriage & tracks, swing system, boom/stick/attachment, cooling system, fuel system, cab & controls, and final inspection.',
  '[
    {"id": "visual-inspection-1", "title": "Exterior and Undercarriage Overview", "description": "Walk around the excavator and visually inspect for any obvious damage, loose components, or fluid leaks (oil, hydraulic fluid, coolant). Check that the undercarriage is clear of excessive mud or debris that could hide issues or impede movement.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-2", "title": "Safety Decals and Labels", "description": "Ensure all safety decals, operational labels, and warning signs are present and legible, including load charts (if applicable) and instructional placards.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-3", "title": "Swing Bearing and House Swing Area", "description": "Visually inspect the swing bearing area (where the upper structure meets the undercarriage) for excess grease purging, metal shavings, or debris. Check that the slew ring guard (if present) is secure. Look for any indication of abnormal movement or gaps in the swing bearing.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-4", "title": "Boom, Stick, and Attachment Condition", "description": "Examine the boom and stick (arm) for cracks, dents, or structural damage, especially around welds and connection points. Check the attachment (bucket or other tool) for cracked welds, worn or missing teeth, or damaged cutting edges.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-5", "title": "Cylinders and Hoses (External)", "description": "Inspect all visible hydraulic cylinders (boom lift, arm (stick) cylinder, bucket cylinder, and any auxiliary cylinders) for signs of oil leaks at seals or damage to the rod. Also check exposed hydraulic hoses and tube lines along the boom and stick for cracks, wear, or leaks.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-6", "title": "Tracks and Ground Contact", "description": "Walk around the tracks (or wheels if a wheeled excavator) to check for proper tension and any noticeable damage. Ensure track pads/shoes are secure and not excessively worn or missing bolts. Look for any foreign objects lodged in the tracks or sprockets.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-7", "title": "Handrails, Steps, and Guards", "description": "Verify that all handrails, grab handles, and steps are secure and undamaged. Ensure anti-slip surfaces on steps and the upper structure walkway are in good condition. Check that protective guards and covers (for example, over the swing motor, radiator, etc.) are in place and secure.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-8", "title": "Counterweight and Carbody", "description": "Inspect the counterweight for any damage, cracks, or loose mounting bolts (if removable type). Ensure the carbody (the main lower frame) has no visible structural damage or missing bolts/nuts.", "required": true, "section": "Visual Inspection"},
    {"id": "visual-inspection-9", "title": "House Slew Limit Stop (if equipped)", "description": "If the excavator has mechanical swing stops or a house lock (transport pin), verify it is stored properly or engaged only as needed, and check that the mechanism is not damaged.", "required": true, "section": "Visual Inspection"},
    {"id": "engine-compartment-10", "title": "Remove Debris and Clean Compartment", "description": "Open the engine hood or covers and clear out any accumulated debris, leaves, or dirt from the engine compartment, especially around the radiator and coolers.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-11", "title": "Engine Oil Level and Filter", "description": "Check the engine oil level using the dipstick and top off if needed with the correct grade. If a scheduled oil change is due, drain the oil and replace the oil filter and oil per manufacturer instructions.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-12", "title": "Fuel Filters and Water Separator", "description": "Inspect the primary and secondary fuel filters for water or sediment. Drain the water separator (bowl or filter drain) of any water and replace fuel filters if due or if poor engine performance is noted.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-13", "title": "Air Filter and Intake", "description": "Check the engine air filter restriction indicator (if equipped) and remove the air filter element. Tap out or blow out dust (if reusable) and replace it if it''s clogged or according to service interval. Wipe out the inside of the air cleaner housing and ensure the intake piping is secure with no cracks.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-14", "title": "Belts and Engine Accessories", "description": "Inspect all drive belts (fan belt, alternator belt, AC compressor belt if present) for tension and signs of wear (cracks or glazing). Adjust belt tension or replace belts as necessary. Check engine accessory components (alternator, compressor) are securely mounted.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-15", "title": "Engine Coolant Level", "description": "Verify coolant is at the proper level in the radiator or expansion tank (only open cap when engine is cool). Add coolant if low, using the correct type and mixture. Examine visible coolant hoses and connections for leaks or deterioration.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-16", "title": "Engine Cooling Fan and Shroud", "description": "With engine off, inspect the fan for any damage (bent or cracked blades) and test for excessive play indicating a worn bearing. Ensure the fan shroud is properly aligned and secured to prevent contact with the fan.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-17", "title": "Exhaust System", "description": "Inspect the exhaust manifold, turbocharger (if equipped), and muffler for soot marks or carbon buildup that could indicate leaks. Ensure exhaust pipes and mounts are secure and check that the rain cap (if present on the exhaust outlet) opens freely.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-18", "title": "Engine Leaks and Mounts", "description": "Look over the engine block, oil pan, valve cover, and fuel injection pump for any signs of fluid leaks (oil, fuel, coolant). Check engine mounts for any broken bolts or deteriorated rubber, indicating the engine may not be securely seated.", "required": true, "section": "Engine Compartment"},
    {"id": "engine-compartment-19", "title": "Pre-Start Engine Condition", "description": "Before starting the engine, check critical fluid levels including engine oil, coolant, and also hydraulic oil (sight gauge) to ensure everything is filled. Verify no tools or rags are left in the compartment and that all caps (oil fill, dipstick, coolant) are secured.", "required": true, "section": "Engine Compartment"},
    {"id": "electrical-system-20", "title": "Battery and Connections", "description": "Inspect the battery (or batteries) for secure mounting, clean terminals, and no cracks or bulging in the case. Clean any corrosion from terminals and cables. Check battery electrolyte level (if not maintenance-free) or indicator if present, and top up with distilled water if needed.", "required": true, "section": "Electrical System"},
    {"id": "electrical-system-21", "title": "Battery Load Test", "description": "Perform a battery load test or monitor voltage during engine start to ensure the battery can provide sufficient power. Replace the battery if it fails to hold charge or deliver adequate cranking power.", "required": true, "section": "Electrical System"},
    {"id": "electrical-system-22", "title": "Charging and Starting Circuit", "description": "With the engine running, measure alternator output to verify the charging system is functioning. Listen for alternator noise. Inspect starter wiring and connections for tightness and check that the starter motor is securely mounted.", "required": true, "section": "Electrical System"},
    {"id": "electrical-system-23", "title": "Fuses, Relays, and Control Modules", "description": "Open the electrical control box or fuse panel. Check that all fuses are intact and of correct rating, and that no relays are loose. Look for any signs of overheated wires or components. Ensure control modules (ECU, etc.) are firmly connected and show no fault lights, if visible.", "required": true, "section": "Electrical System"},
    {"id": "electrical-system-24", "title": "Lights and Horn", "description": "Activate all exterior lights: check operation of front and rear working lights, travel lights, blinkers/brake lights (if applicable), and beacon or strobe if fitted. Verify the horn works and is loud enough.", "required": true, "section": "Electrical System"},
    {"id": "electrical-system-25", "title": "Operator Display and Gauges", "description": "Turn the ignition on and confirm all warning lights on the operator display illuminate during the self-test and go out after engine start (except those that should remain). Check that gauges read normally.", "required": true, "section": "Electrical System"},
    {"id": "electrical-system-26", "title": "Backup Alarm and Camera (if equipped)", "description": "Put the excavator in reverse to test that the backup alarm sounds. If a rearview camera or other vision system is installed, verify that it powers on and provides a clear image.", "required": true, "section": "Electrical System"},
    {"id": "electrical-system-27", "title": "Wiring Harness and Connectors", "description": "Trace main wiring harnesses for signs of rubbing, loose clamps, exposed wires, or pinched sections through the swing bearing area.", "required": true, "section": "Electrical System"},
    {"id": "hydraulic-system-28", "title": "Hydraulic Oil Level and Temperature", "description": "Check the hydraulic oil level via the sight glass or dipstick with the machine on level ground and implements lowered. Ensure the oil is clean and at correct level.", "required": true, "section": "Hydraulic System"},
    {"id": "hydraulic-system-29", "title": "Hydraulic Filters", "description": "Replace return, pilot, or case drain filters if due. Inspect removed filters for metal shavings.", "required": true, "section": "Hydraulic System"},
    {"id": "hydraulic-system-30", "title": "Hydraulic Pump and Valves", "description": "Inspect the main pump(s) for leaks or loose fittings. Check control valve blocks and solenoids for damage or leakage.", "required": true, "section": "Hydraulic System"},
    {"id": "hydraulic-system-31", "title": "Travel Motors and Swing Motor for Leaks", "description": "Inspect travel motors, swing motor, and swivel joint for leaks or damage.", "required": true, "section": "Hydraulic System"},
    {"id": "hydraulic-system-32", "title": "Auxiliary Hydraulic Circuit", "description": "Inspect auxiliary lines and connectors. Engage aux control briefly to verify flow and relief operation.", "required": true, "section": "Hydraulic System"},
    {"id": "hydraulic-system-33", "title": "Cylinders and Hoses (Detailed)", "description": "Inspect all cylinders for leaks, worn pins, cracked lugs, and damaged hoses.", "required": true, "section": "Hydraulic System"},
    {"id": "hydraulic-system-34", "title": "Hydraulic Tank Cap and Breather", "description": "Ensure tank cap is tight and breather element is clean/unclogged.", "required": true, "section": "Hydraulic System"},
    {"id": "hydraulic-system-35", "title": "Operational Test for Hydraulic Functions", "description": "Cycle all hydraulic functions without load to confirm smooth, responsive operation.", "required": true, "section": "Hydraulic System"},
    {"id": "undercarriage-tracks-36", "title": "Track Tension and Adjustment", "description": "Measure track sag and adjust tension using grease adjuster valve as needed.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "undercarriage-tracks-37", "title": "Track Shoes and Pads", "description": "Inspect shoes/pads for wear, loose bolts, cracks, or damage.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "undercarriage-tracks-38", "title": "Drive Sprockets", "description": "Inspect sprocket teeth for wear or cracks and verify bolt tightness.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "undercarriage-tracks-39", "title": "Rollers and Idlers", "description": "Inspect rollers and idlers for leaks, wear, and free movement.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "undercarriage-tracks-40", "title": "Track Frame and Guards", "description": "Inspect track frame for cracks or loose guards.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "undercarriage-tracks-41", "title": "Final Drives (Travel Gearboxes)", "description": "Check final drive oil level and inspect magnetic plugs for metal.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "undercarriage-tracks-42", "title": "Swing Bearing Bolts", "description": "Visually inspect swing bearing bolts for looseness or missing bolts.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "undercarriage-tracks-43", "title": "Cleaning and Debris Removal", "description": "Remove mud, rocks, or debris from undercarriage components.", "required": true, "section": "Undercarriage & Tracks"},
    {"id": "swing-system-44", "title": "Swing Brake Function", "description": "Test swing brake or lock for proper engagement and release.", "required": true, "section": "Swing System"},
    {"id": "swing-system-45", "title": "Swing Gearbox Oil", "description": "Check oil level/condition in swing drive gearbox.", "required": true, "section": "Swing System"},
    {"id": "swing-system-46", "title": "Swing Bearing and Grease", "description": "Grease swing bearing fittings and inspect gear teeth if visible.", "required": true, "section": "Swing System"},
    {"id": "swing-system-47", "title": "Swing Motor and Relief", "description": "Inspect swing motor for leaks and verify smooth swing operation.", "required": true, "section": "Swing System"},
    {"id": "swing-system-48", "title": "Swing Seal Guard", "description": "Inspect swing bearing seal integrity and confirm guards are secure.", "required": true, "section": "Swing System"},
    {"id": "boom-stick-attachment-49", "title": "Boom and Stick Structural Check", "description": "Inspect for cracks, bends, or stressed welds along boom and stick.", "required": true, "section": "Boom, Stick & Attachment"},
    {"id": "boom-stick-attachment-50", "title": "Pins and Bushings Wear", "description": "Check all joints for excessive play, wear particles, or missing retainers.", "required": true, "section": "Boom, Stick & Attachment"},
    {"id": "boom-stick-attachment-51", "title": "Attachment Coupler (if equipped)", "description": "Inspect coupler structure, locking mechanism, and safety pins.", "required": true, "section": "Boom, Stick & Attachment"},
    {"id": "boom-stick-attachment-52", "title": "Bucket/Attachment Condition", "description": "Inspect bucket teeth, cutting edges, or attachments for wear or cracks.", "required": true, "section": "Boom, Stick & Attachment"},
    {"id": "boom-stick-attachment-53", "title": "Cylinder Attachments", "description": "Check cylinder mounting points for cracks or loose hardware.", "required": true, "section": "Boom, Stick & Attachment"},
    {"id": "boom-stick-attachment-54", "title": "Lubrication of Front End", "description": "Grease all linkage and pivot points until clean grease extrudes.", "required": true, "section": "Boom, Stick & Attachment"},
    {"id": "boom-stick-attachment-55", "title": "Auxiliary Attachment Hoses", "description": "Inspect hoses on thumbs/attachments for leaks or abrasion.", "required": true, "section": "Boom, Stick & Attachment"},
    {"id": "cooling-system-56", "title": "Radiator and Coolers", "description": "Clean radiator, oil cooler, and charge air cooler fins.", "required": true, "section": "Cooling System"},
    {"id": "cooling-system-57", "title": "Coolant Strength and Level", "description": "Test coolant for freeze/boil protection and proper level.", "required": true, "section": "Cooling System"},
    {"id": "cooling-system-58", "title": "Cooling System Leaks", "description": "Inspect radiator, hoses, clamps, thermostat housing, and engine block.", "required": true, "section": "Cooling System"},
    {"id": "cooling-system-59", "title": "Water Pump and Fan Drive", "description": "Inspect weep hole for leaks and check for pulley play or belt issues.", "required": true, "section": "Cooling System"},
    {"id": "cooling-system-60", "title": "Engine Temperature Performance", "description": "Warm engine and monitor coolant temperature stability.", "required": true, "section": "Cooling System"},
    {"id": "cooling-system-61", "title": "Cab Heater Core (if applicable)", "description": "Verify heater produces warm air and hoses are leak-free.", "required": true, "section": "Cooling System"},
    {"id": "fuel-system-62", "title": "Fuel Tank and Cap", "description": "Inspect tank integrity and verify cap seals and vents properly.", "required": true, "section": "Fuel System"},
    {"id": "fuel-system-63", "title": "Fuel Lines and Injectors", "description": "Check all lines for cracks, leaks, or loose fittings. Inspect injector area.", "required": true, "section": "Fuel System"},
    {"id": "fuel-system-64", "title": "Water Separator Operation", "description": "Drain separator and check indicator functionality.", "required": true, "section": "Fuel System"},
    {"id": "fuel-system-65", "title": "Fuel Filter Change (if due)", "description": "Replace fuel filters per interval and bleed air from system.", "required": true, "section": "Fuel System"},
    {"id": "fuel-system-66", "title": "Turbocharger & Aftertreatment (if applicable)", "description": "Inspect DEF tank/lines, DPF regen status, and turbocharger for leaks.", "required": true, "section": "Fuel System"},
    {"id": "cab-controls-67", "title": "Operator Seat and Seat Belt", "description": "Inspect seat/seat belt condition and verify latch/alarm operation.", "required": true, "section": "Cab & Controls"},
    {"id": "cab-controls-68", "title": "Control Levers and Joysticks", "description": "Confirm smooth movement and neutral return.", "required": true, "section": "Cab & Controls"},
    {"id": "cab-controls-69", "title": "Pedals and Travel Controls", "description": "Clean around pedals and verify proper operation.", "required": true, "section": "Cab & Controls"},
    {"id": "cab-controls-70", "title": "Monitor Panel and Alerts", "description": "Verify warning lights, service codes, and maintenance indicators.", "required": true, "section": "Cab & Controls"},
    {"id": "cab-controls-71", "title": "Climate Controls", "description": "Test AC/heater, fan speeds, and replace cab air filter if needed.", "required": true, "section": "Cab & Controls"},
    {"id": "cab-controls-72", "title": "Wipers and Washers", "description": "Verify wiper/washers operate and replace blades if worn.", "required": true, "section": "Cab & Controls"},
    {"id": "cab-controls-73", "title": "Cab Accessories and Safety", "description": "Check fire extinguisher, operator manual, and emergency exits.", "required": true, "section": "Cab & Controls"},
    {"id": "cab-controls-74", "title": "Parking Brake and Hold Function", "description": "Verify parking brake or travel lock operates as designed.", "required": true, "section": "Cab & Controls"},
    {"id": "final-inspection-75", "title": "Engine Start and Idle", "description": "Start engine and verify warning lights clear and idle is smooth.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-76", "title": "Control Function Test", "description": "Test boom, stick, bucket, and swing functions for smooth response.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-77", "title": "Travel and Brake Test", "description": "Drive forward/reverse; verify even tracking and proper braking.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-78", "title": "High Speed Travel (if equipped)", "description": "Test two-speed travel for smooth shifting and operation.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-79", "title": "Attachment Operation Test", "description": "Test thumbs, breakers, or other attachments for full function.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-80", "title": "Warning Devices Test", "description": "Test horn, backup alarm, and other warning devices.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-81", "title": "Monitoring During Operation", "description": "Observe engine/hydraulic temps, pressure, and gauge behavior.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-82", "title": "Leak Check Post-Operation", "description": "Inspect machine after shutdown for fresh leaks.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-83", "title": "House Swing Parking", "description": "Park machine with house aligned and swing lock engaged if needed.", "required": true, "section": "Final Inspection"},
    {"id": "final-inspection-84", "title": "Documentation and Clean-Up", "description": "Record service, apply PM sticker, and clean machine surfaces.", "required": true, "section": "Final Inspection"}
  ]'::jsonb,
  true,
  'bb0e8400-e29b-41d4-a716-446655440001'::uuid,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM "public"."pm_checklist_templates"
  WHERE "id" = 'cc0e8400-e29b-41d4-a716-446655440005'::uuid
)
ON CONFLICT (id) DO NOTHING;
