import {
  DEFAULT_COLUMN_ORDER,
  DEFAULT_COLUMN_SIZING,
  DEFAULT_COLUMN_VISIBILITY,
} from '@/features/inventory/components/inventoryTableColumns';
import type { InventorySavedView } from '@/features/inventory/types/inventory';

const BUILT_IN_IDS = {
  default: 'builtin-default',
  purchasing: 'builtin-purchasing',
  lowStockReview: 'builtin-low-stock-review',
  fieldTechnician: 'builtin-field-technician',
  accounting: 'builtin-accounting',
} as const;

export const INVENTORY_BUILT_IN_VIEWS: InventorySavedView[] = [
  {
    id: BUILT_IN_IDS.default,
    name: 'Default',
    filters: { sortBy: 'name', sortOrder: 'asc' },
    quickFilters: [],
    columnVisibility: { ...DEFAULT_COLUMN_VISIBILITY },
    columnOrder: [...DEFAULT_COLUMN_ORDER],
    columnSizing: { ...DEFAULT_COLUMN_SIZING },
    density: 'compact',
  },
  {
    id: BUILT_IN_IDS.purchasing,
    name: 'Purchasing',
    filters: { sortBy: 'reorder_priority', sortOrder: 'desc' },
    quickFilters: ['reorder-needed', 'missing-unit-cost'],
    columnVisibility: {
      ...DEFAULT_COLUMN_VISIBILITY,
      name: true,
      sku: true,
      quantity_on_hand: true,
      low_stock_threshold: true,
      default_unit_cost: true,
      location: true,
      status: true,
      external_id: false,
      alternate_groups: false,
      description: false,
      created_at: false,
      updated_at: false,
      last_adjusted_at: false,
    },
    columnOrder: [
      'name',
      'sku',
      'quantity_on_hand',
      'low_stock_threshold',
      'default_unit_cost',
      'location',
      'status',
      'external_id',
      'alternate_groups',
      'description',
      'created_at',
      'updated_at',
      'last_adjusted_at',
    ],
    columnSizing: { ...DEFAULT_COLUMN_SIZING },
    density: 'compact',
  },
  {
    id: BUILT_IN_IDS.lowStockReview,
    name: 'Low Stock Review',
    filters: { sortBy: 'quantity_on_hand', sortOrder: 'asc' },
    quickFilters: ['low-stock', 'out-of-stock', 'negative-stock'],
    columnVisibility: {
      ...DEFAULT_COLUMN_VISIBILITY,
      name: true,
      sku: true,
      quantity_on_hand: true,
      low_stock_threshold: true,
      location: true,
      status: true,
      alternate_groups: true,
      default_unit_cost: false,
      external_id: false,
      description: false,
      created_at: false,
      updated_at: false,
      last_adjusted_at: true,
    },
    columnOrder: [
      'name',
      'quantity_on_hand',
      'low_stock_threshold',
      'status',
      'location',
      'alternate_groups',
      'last_adjusted_at',
      'sku',
      'external_id',
      'default_unit_cost',
      'description',
      'created_at',
      'updated_at',
    ],
    columnSizing: { ...DEFAULT_COLUMN_SIZING },
    density: 'compact',
  },
  {
    id: BUILT_IN_IDS.fieldTechnician,
    name: 'Field Technician',
    filters: { sortBy: 'name', sortOrder: 'asc' },
    quickFilters: ['has-alternates'],
    columnVisibility: {
      ...DEFAULT_COLUMN_VISIBILITY,
      name: true,
      sku: true,
      quantity_on_hand: true,
      location: true,
      status: true,
      alternate_groups: true,
      external_id: false,
      low_stock_threshold: false,
      default_unit_cost: false,
      description: false,
      created_at: false,
      updated_at: false,
      last_adjusted_at: false,
    },
    columnOrder: [
      'name',
      'quantity_on_hand',
      'location',
      'status',
      'alternate_groups',
      'sku',
      'external_id',
      'low_stock_threshold',
      'default_unit_cost',
      'description',
      'created_at',
      'updated_at',
      'last_adjusted_at',
    ],
    columnSizing: { ...DEFAULT_COLUMN_SIZING },
    density: 'comfortable',
  },
  {
    id: BUILT_IN_IDS.accounting,
    name: 'Accounting',
    filters: { sortBy: 'inventory_value', sortOrder: 'desc' },
    quickFilters: ['missing-unit-cost'],
    columnVisibility: {
      ...DEFAULT_COLUMN_VISIBILITY,
      name: true,
      sku: true,
      quantity_on_hand: true,
      default_unit_cost: true,
      location: false,
      status: false,
      external_id: true,
      low_stock_threshold: false,
      alternate_groups: false,
      description: false,
      created_at: true,
      updated_at: true,
      last_adjusted_at: false,
    },
    columnOrder: [
      'name',
      'sku',
      'quantity_on_hand',
      'default_unit_cost',
      'external_id',
      'created_at',
      'updated_at',
      'location',
      'status',
      'low_stock_threshold',
      'alternate_groups',
      'description',
      'last_adjusted_at',
    ],
    columnSizing: { ...DEFAULT_COLUMN_SIZING },
    density: 'compact',
  },
];

export function isBuiltInViewId(viewId: string): boolean {
  return INVENTORY_BUILT_IN_VIEWS.some((v) => v.id === viewId);
}
