// Audit explorer presentation strings. Audit event payloads and exported files remain unchanged.
export const auditExplorerResources = {
  en: { auditExplorer: {
    emptyTitle: 'No audit entries found', emptyHint: 'Try adjusting your filters or widening the time range.', showing: 'Showing {{start}}–{{end}} of {{total}} entries', previous: 'Previous', next: 'Next', pageOf: 'Page {{page}} of {{total}}', metrics: 'Key Metrics', timeline: 'Timeline', events: 'Events', preparingExport: 'Preparing export...', noExportRecords: 'No matching records found.', exportingRecords: 'Exporting {{current}} of {{total}} records...',
    resetLayout: 'Reset layout', dragTitle: 'Drag to rearrange', dragSection: 'Drag to move the {{name}} section', moveUp: 'Move {{name}} section up', moveDown: 'Move {{name}} section down', expand: 'Expand the {{name}} section', collapse: 'Collapse the {{name}} section', totalEntries: 'Total Entries', createdRecords: 'Records Created', updatedRecords: 'Records Updated', deletedRecords: 'Records Deleted', noActivity: 'No activity in this range', widenRange: 'Widen the time range above',
    listAria: 'Audit log entries', selectEntry: 'Select audit entry for {{name}}', unknownEntity: 'unknown entity', unknown: 'Unknown', noChanges: 'No changes', entry: 'Audit Entry', noSelection: 'No entry selected', selectHint: 'Select an entry on the left to inspect.', clearSelection: 'Clear selection', copyClipboard: 'Copy to clipboard', copyMarkdown: 'Copy Markdown', copyJson: 'Copy JSON', copied: 'Copied', overview: 'Overview', changes: 'Changes', entryDetails: 'Entry Details', date: 'Date', entityName: 'Entity Name', entityType: 'Entity Type', action: 'Action', changedBy: 'Changed By', fieldsCount: '{{count}} fields', identifiers: 'Identifiers', entryId: 'Entry ID', entityId: 'Entity ID', actorId: 'Actor ID', organizationId: 'Org ID', metadata: 'Metadata', noFieldChanges: 'No field changes recorded.',
    selectedCount: '{{count}} entries selected', clear: 'Clear', bulkHint: 'Multiple entries are selected, so this pane works on the group. Export the selected log entries or clear the selection to inspect a single entry.', exportSelection: 'Export selection', exporting: 'Exporting…', restricted: 'Exports are available to organization owners and administrators.', selectionTip: 'Tip: use the row checkboxes, Ctrl/Cmd-click to toggle, or Shift-click to select a range.', exportedCount: 'Exported {{count}} entries', exportFailed: 'Export failed. Please try again.',
    empty: '(empty)', yes: 'Yes', no: 'No', noChangesRecorded: 'No changes recorded', moreChanges: '+{{count}} more changes', setTo: '{{label}}: set to {{value}}', cleared: '{{label}}: cleared', twoChanged: '{{first}} and {{second}} changed', threeChanged: '{{first}}, {{second}}, and {{third}} changed', otherFields: '{{first}}, {{second}}, and {{count}} other fields',
    fields: {
      name: 'Name', status: 'Status', location: 'Location', team_id: 'Team', warranty_expiration: 'Warranty Expiration', working_hours: 'Working Hours', last_maintenance: 'Last Maintenance', notes: 'Notes', image_url: 'Image', manufacturer: 'Manufacturer', model: 'Model', serial_number: 'Serial Number', default_pm_template_id: 'PM Template', installation_date: 'Installation Date', customer_id: 'Customer', custom_attributes: 'Custom Attributes', last_known_location: 'Last Known Location', title: 'Title', description: 'Description', priority: 'Priority', assignee_id: 'Assignee', assignee_name: 'Assignee Name', due_date: 'Due Date', completed_date: 'Completed Date', estimated_hours: 'Estimated Hours', equipment_id: 'Equipment', quantity_on_hand: 'Quantity', low_stock_threshold: 'Low Stock Threshold', default_unit_cost: 'Unit Cost', sku: 'SKU', template_id: 'Template', completed_at: 'Completed At', completed_by: 'Completed By', role: 'Role', invited_by: 'Invited By', user_id: 'User',
    },
  } },
  vi: { auditExplorer: {
    emptyTitle: 'Không tìm thấy bản ghi kiểm toán', emptyHint: 'Hãy điều chỉnh bộ lọc hoặc mở rộng khoảng thời gian.', showing: 'Hiển thị {{start}}–{{end}} / {{total}} bản ghi', previous: 'Trước', next: 'Sau', pageOf: 'Trang {{page}} / {{total}}', metrics: 'Chỉ số chính', timeline: 'Dòng thời gian', events: 'Sự kiện', preparingExport: 'Đang chuẩn bị xuất...', noExportRecords: 'Không tìm thấy bản ghi phù hợp.', exportingRecords: 'Đang xuất {{current}} / {{total}} bản ghi...',
    resetLayout: 'Đặt lại bố cục', dragTitle: 'Kéo để sắp xếp lại', dragSection: 'Kéo để di chuyển phần {{name}}', moveUp: 'Di chuyển phần {{name}} lên', moveDown: 'Di chuyển phần {{name}} xuống', expand: 'Mở rộng phần {{name}}', collapse: 'Thu gọn phần {{name}}', totalEntries: 'Tổng bản ghi', createdRecords: 'Bản ghi đã tạo', updatedRecords: 'Bản ghi đã cập nhật', deletedRecords: 'Bản ghi đã xóa', noActivity: 'Không có hoạt động trong khoảng thời gian này', widenRange: 'Mở rộng khoảng thời gian ở trên',
    listAria: 'Các bản ghi kiểm toán', selectEntry: 'Chọn bản ghi kiểm toán của {{name}}', unknownEntity: 'đối tượng không rõ', unknown: 'Không rõ', noChanges: 'Không có thay đổi', entry: 'Bản ghi kiểm toán', noSelection: 'Chưa chọn bản ghi', selectHint: 'Chọn bản ghi bên trái để xem chi tiết.', clearSelection: 'Bỏ lựa chọn', copyClipboard: 'Sao chép vào bộ nhớ tạm', copyMarkdown: 'Sao chép Markdown', copyJson: 'Sao chép JSON', copied: 'Đã sao chép', overview: 'Tổng quan', changes: 'Thay đổi', entryDetails: 'Chi tiết bản ghi', date: 'Ngày', entityName: 'Tên đối tượng', entityType: 'Loại đối tượng', action: 'Hành động', changedBy: 'Người thay đổi', fieldsCount: '{{count}} trường', identifiers: 'Mã định danh', entryId: 'ID bản ghi', entityId: 'ID đối tượng', actorId: 'ID người thực hiện', organizationId: 'ID tổ chức', metadata: 'Siêu dữ liệu', noFieldChanges: 'Không ghi nhận thay đổi trường nào.',
    selectedCount: 'Đã chọn {{count}} bản ghi', clear: 'Bỏ chọn', bulkHint: 'Đã chọn nhiều bản ghi. Bạn có thể xuất các bản ghi này hoặc bỏ chọn để xem chi tiết từng bản ghi.', exportSelection: 'Xuất mục đã chọn', exporting: 'Đang xuất…', restricted: 'Chỉ chủ sở hữu và quản trị viên tổ chức mới có thể xuất.', selectionTip: 'Mẹo: dùng hộp chọn ở từng dòng, Ctrl/Cmd-nhấp để bật/tắt, hoặc Shift-nhấp để chọn một dải.', exportedCount: 'Đã xuất {{count}} bản ghi', exportFailed: 'Xuất thất bại. Vui lòng thử lại.',
    empty: '(trống)', yes: 'Có', no: 'Không', noChangesRecorded: 'Không ghi nhận thay đổi', moreChanges: '+{{count}} thay đổi khác', setTo: '{{label}}: đặt thành {{value}}', cleared: '{{label}}: đã xóa giá trị', twoChanged: '{{first}} và {{second}} đã thay đổi', threeChanged: '{{first}}, {{second}} và {{third}} đã thay đổi', otherFields: '{{first}}, {{second}} và {{count}} trường khác',
    fields: {
      name: 'Tên', status: 'Trạng thái', location: 'Vị trí', team_id: 'Đội', warranty_expiration: 'Hết hạn bảo hành', working_hours: 'Giờ hoạt động', last_maintenance: 'Bảo trì gần nhất', notes: 'Ghi chú', image_url: 'Ảnh', manufacturer: 'Nhà sản xuất', model: 'Mẫu', serial_number: 'Số sê-ri', default_pm_template_id: 'Mẫu bảo trì định kỳ', installation_date: 'Ngày lắp đặt', customer_id: 'Khách hàng', custom_attributes: 'Thuộc tính tùy chỉnh', last_known_location: 'Vị trí gần nhất', title: 'Tiêu đề', description: 'Mô tả', priority: 'Độ ưu tiên', assignee_id: 'Người phụ trách', assignee_name: 'Tên người phụ trách', due_date: 'Hạn hoàn thành', completed_date: 'Ngày hoàn thành', estimated_hours: 'Giờ dự kiến', equipment_id: 'Thiết bị', quantity_on_hand: 'Số lượng', low_stock_threshold: 'Ngưỡng tồn kho thấp', default_unit_cost: 'Đơn giá', sku: 'SKU', template_id: 'Mẫu', completed_at: 'Hoàn thành lúc', completed_by: 'Người hoàn thành', role: 'Vai trò', invited_by: 'Người mời', user_id: 'Người dùng',
    },
  } },
  ko: { auditExplorer: {
    emptyTitle: '감사 기록을 찾을 수 없습니다', emptyHint: '필터를 조정하거나 시간 범위를 넓혀 보세요.', showing: '{{total}}개 기록 중 {{start}}–{{end}} 표시', previous: '이전', next: '다음', pageOf: '{{page}} / {{total}}페이지', metrics: '주요 지표', timeline: '타임라인', events: '이벤트', preparingExport: '내보내기 준비 중...', noExportRecords: '일치하는 기록이 없습니다.', exportingRecords: '{{total}}개 중 {{current}}개 기록 내보내는 중...',
    resetLayout: '레이아웃 초기화', dragTitle: '드래그하여 순서 변경', dragSection: '{{name}} 섹션을 드래그하여 이동', moveUp: '{{name}} 섹션 위로 이동', moveDown: '{{name}} 섹션 아래로 이동', expand: '{{name}} 섹션 펼치기', collapse: '{{name}} 섹션 접기', totalEntries: '전체 기록', createdRecords: '생성된 기록', updatedRecords: '업데이트된 기록', deletedRecords: '삭제된 기록', noActivity: '이 기간에 활동이 없습니다', widenRange: '위에서 시간 범위를 넓혀 보세요',
    listAria: '감사 기록', selectEntry: '{{name}}의 감사 기록 선택', unknownEntity: '알 수 없는 대상', unknown: '알 수 없음', noChanges: '변경 사항 없음', entry: '감사 기록', noSelection: '선택한 기록 없음', selectHint: '왼쪽에서 기록을 선택해 확인하세요.', clearSelection: '선택 지우기', copyClipboard: '클립보드에 복사', copyMarkdown: 'Markdown 복사', copyJson: 'JSON 복사', copied: '복사됨', overview: '개요', changes: '변경 사항', entryDetails: '기록 상세', date: '날짜', entityName: '대상 이름', entityType: '대상 유형', action: '작업', changedBy: '변경자', fieldsCount: '필드 {{count}}개', identifiers: '식별자', entryId: '기록 ID', entityId: '대상 ID', actorId: '작업자 ID', organizationId: '조직 ID', metadata: '메타데이터', noFieldChanges: '기록된 필드 변경이 없습니다.',
    selectedCount: '{{count}}개 기록 선택', clear: '선택 해제', bulkHint: '여러 기록이 선택되었습니다. 선택 항목을 내보내거나 선택을 해제하여 개별 기록을 확인하세요.', exportSelection: '선택 항목 내보내기', exporting: '내보내는 중…', restricted: '조직 소유자와 관리자만 내보낼 수 있습니다.', selectionTip: '팁: 행의 체크박스, Ctrl/Cmd+클릭으로 선택 전환, Shift+클릭으로 범위를 선택하세요.', exportedCount: '{{count}}개 기록을 내보냈습니다', exportFailed: '내보내기에 실패했습니다. 다시 시도하세요.',
    empty: '(비어 있음)', yes: '예', no: '아니요', noChangesRecorded: '기록된 변경 사항 없음', moreChanges: '+{{count}}개 변경 사항', setTo: '{{label}}: {{value}}(으)로 설정', cleared: '{{label}}: 지움', twoChanged: '{{first}} 및 {{second}} 변경됨', threeChanged: '{{first}}, {{second}} 및 {{third}} 변경됨', otherFields: '{{first}}, {{second}} 및 다른 필드 {{count}}개',
    fields: {
      name: '이름', status: '상태', location: '위치', team_id: '팀', warranty_expiration: '보증 만료일', working_hours: '작동 시간', last_maintenance: '최근 정비', notes: '메모', image_url: '이미지', manufacturer: '제조사', model: '모델', serial_number: '일련번호', default_pm_template_id: '예방 정비 템플릿', installation_date: '설치일', customer_id: '고객', custom_attributes: '사용자 지정 속성', last_known_location: '마지막 위치', title: '제목', description: '설명', priority: '우선순위', assignee_id: '담당자', assignee_name: '담당자 이름', due_date: '마감일', completed_date: '완료일', estimated_hours: '예상 시간', equipment_id: '장비', quantity_on_hand: '수량', low_stock_threshold: '최소 재고 기준', default_unit_cost: '단가', sku: 'SKU', template_id: '템플릿', completed_at: '완료 시각', completed_by: '완료자', role: '역할', invited_by: '초대한 사람', user_id: '사용자',
    },
  } },
} as const;
