export const auditLogControlsResources = {
  en: { auditLogControls: {
    noOrganization: 'No Organization Selected', chooseOrganization: 'Please select an organization to view the audit log.', accessDenied: 'Access Denied', adminOnly: 'The audit log contains sensitive, high-privilege information and is only available to organization owners and administrators.', title: 'Audit Log', introduction: "Track all changes made to your organization's data for compliance and accountability.", regulatory: 'Regulatory compliance', regulatoryHelp: 'This audit log helps you comply with OSHA, DOT, and other regulatory requirements by maintaining a complete record of all equipment, work order, and inventory changes. Records are immutable and cannot be modified or deleted.',
    searchHint: 'Search by name or user...', searchLabel: 'Search audit entries by entity name or user', clearSearch: 'Clear search', entries: '{{count}} entries', active: 'Active:', activeTime: 'Time: {{preset}}', resetTime: 'Reset time range to default', clearEntity: 'Clear entity type filter', clearAction: 'Clear action filter', clearAll: 'Clear all', auditSubject: 'audit log', filters: 'Filters', filter: 'Filter', filterAudit: 'Filter audit log', filterAuditActive: 'Filter audit log, {{count}} active', entityType: 'Entity Type', filterEntity: 'Filter by entity type', allTypes: 'All Types', action: 'Action', filterAction: 'Filter by action', allActions: 'All Actions', clearFilters: 'Clear all filters',
    last15m: 'Last 15m', last1h: 'Last 1h', last24h: 'Last 24h', last7d: 'Last 7d', last30d: 'Last 30d', allTime: 'All time', custom: 'Custom', preset: 'Time range preset', minutes15: 'Last 15 minutes', hour1: 'Last 1 hour', hours24: 'Last 24 hours', days7: 'Last 7 days', days30: 'Last 30 days', short15m: '15m', short1h: '1h', short24h: '24h', short7d: '7d', short30d: '30d', all: 'All', customDateRange: 'Custom date range', customRange: 'Custom range', from: 'From', to: 'To', customStart: 'Custom range start date', customEnd: 'Custom range end date', cancel: 'Cancel', apply: 'Apply',
    equipment: 'Equipment', work_order: 'Work Order', inventory_item: 'Inventory Item', preventative_maintenance: 'PM Checklist', organization_member: 'Organization Member', team_member: 'Team Member', team: 'Team', pm_template: 'PM Template', INSERT: 'Created', UPDATE: 'Updated', DELETE: 'Deleted',
    download: 'Download', downloadAudit: 'Download audit log', exportRestricted: 'Export is available to organization owners and admins only', exportFormat: 'Export format', csvDescription: 'Comma-separated values', jsonDescription: 'Structured data format',
  } },
  vi: { auditLogControls: {
    noOrganization: 'Chưa chọn tổ chức', chooseOrganization: 'Vui lòng chọn tổ chức để xem nhật ký kiểm toán.', accessDenied: 'Không có quyền truy cập', adminOnly: 'Nhật ký kiểm toán chứa thông tin nhạy cảm và chỉ dành cho chủ sở hữu hoặc quản trị viên tổ chức.', title: 'Nhật ký kiểm toán', introduction: 'Theo dõi mọi thay đổi dữ liệu của tổ chức để hỗ trợ tuân thủ và xác định trách nhiệm.', regulatory: 'Tuân thủ quy định', regulatoryHelp: 'Nhật ký này hỗ trợ việc tuân thủ yêu cầu OSHA, DOT và các quy định khác bằng cách lưu toàn bộ thay đổi về thiết bị, phiếu công việc và tồn kho. Bản ghi là bất biến và không thể sửa hoặc xóa.',
    searchHint: 'Tìm theo tên hoặc người dùng...', searchLabel: 'Tìm bản ghi kiểm toán theo tên đối tượng hoặc người dùng', clearSearch: 'Xóa tìm kiếm', entries: '{{count}} bản ghi', active: 'Đang áp dụng:', activeTime: 'Thời gian: {{preset}}', resetTime: 'Đặt lại khoảng thời gian mặc định', clearEntity: 'Xóa bộ lọc loại đối tượng', clearAction: 'Xóa bộ lọc hành động', clearAll: 'Xóa tất cả', auditSubject: 'nhật ký kiểm toán', filters: 'Bộ lọc', filter: 'Lọc', filterAudit: 'Lọc nhật ký kiểm toán', filterAuditActive: 'Lọc nhật ký kiểm toán, {{count}} bộ lọc đang áp dụng', entityType: 'Loại đối tượng', filterEntity: 'Lọc theo loại đối tượng', allTypes: 'Mọi loại', action: 'Hành động', filterAction: 'Lọc theo hành động', allActions: 'Mọi hành động', clearFilters: 'Xóa tất cả bộ lọc',
    last15m: '15 phút qua', last1h: '1 giờ qua', last24h: '24 giờ qua', last7d: '7 ngày qua', last30d: '30 ngày qua', allTime: 'Mọi lúc', custom: 'Tùy chỉnh', preset: 'Khoảng thời gian có sẵn', minutes15: '15 phút qua', hour1: '1 giờ qua', hours24: '24 giờ qua', days7: '7 ngày qua', days30: '30 ngày qua', short15m: '15p', short1h: '1g', short24h: '24g', short7d: '7ng', short30d: '30ng', all: 'Tất cả', customDateRange: 'Khoảng ngày tùy chỉnh', customRange: 'Khoảng ngày tùy chỉnh', from: 'Từ', to: 'Đến', customStart: 'Ngày bắt đầu tùy chỉnh', customEnd: 'Ngày kết thúc tùy chỉnh', cancel: 'Hủy', apply: 'Áp dụng',
    equipment: 'Thiết bị', work_order: 'Phiếu công việc', inventory_item: 'Mặt hàng tồn kho', preventative_maintenance: 'Danh sách kiểm tra bảo trì định kỳ', organization_member: 'Thành viên tổ chức', team_member: 'Thành viên đội', team: 'Đội', pm_template: 'Mẫu bảo trì định kỳ', INSERT: 'Đã tạo', UPDATE: 'Đã cập nhật', DELETE: 'Đã xóa',
    download: 'Tải xuống', downloadAudit: 'Tải nhật ký kiểm toán', exportRestricted: 'Chỉ chủ sở hữu và quản trị viên tổ chức mới có thể xuất dữ liệu', exportFormat: 'Định dạng xuất', csvDescription: 'Các giá trị phân tách bằng dấu phẩy', jsonDescription: 'Định dạng dữ liệu có cấu trúc',
  } },
  ko: { auditLogControls: {
    noOrganization: '조직이 선택되지 않음', chooseOrganization: '감사 로그를 보려면 조직을 선택하세요.', accessDenied: '접근 거부', adminOnly: '감사 로그에는 민감한 고권한 정보가 포함되어 있으며 조직 소유자와 관리자만 볼 수 있습니다.', title: '감사 로그', introduction: '규정 준수와 책임 추적을 위해 조직 데이터의 모든 변경 내역을 확인하세요.', regulatory: '규정 준수', regulatoryHelp: '이 감사 로그는 장비, 작업 지시, 재고의 모든 변경 내역을 보관하여 OSHA, DOT 및 기타 규정 요구사항 준수에 도움이 됩니다. 기록은 불변이며 수정하거나 삭제할 수 없습니다.',
    searchHint: '이름 또는 사용자 검색...', searchLabel: '대상 이름이나 사용자로 감사 기록 검색', clearSearch: '검색 지우기', entries: '기록 {{count}}건', active: '적용 중:', activeTime: '시간: {{preset}}', resetTime: '기본 시간 범위로 재설정', clearEntity: '대상 유형 필터 지우기', clearAction: '작업 필터 지우기', clearAll: '모두 지우기', auditSubject: '감사 로그', filters: '필터', filter: '필터', filterAudit: '감사 로그 필터', filterAuditActive: '감사 로그 필터, {{count}}개 적용 중', entityType: '대상 유형', filterEntity: '대상 유형별 필터', allTypes: '모든 유형', action: '작업', filterAction: '작업별 필터', allActions: '모든 작업', clearFilters: '모든 필터 지우기',
    last15m: '최근 15분', last1h: '최근 1시간', last24h: '최근 24시간', last7d: '최근 7일', last30d: '최근 30일', allTime: '전체 기간', custom: '직접 선택', preset: '시간 범위 선택', minutes15: '최근 15분', hour1: '최근 1시간', hours24: '최근 24시간', days7: '최근 7일', days30: '최근 30일', short15m: '15분', short1h: '1시간', short24h: '24시간', short7d: '7일', short30d: '30일', all: '전체', customDateRange: '사용자 지정 날짜 범위', customRange: '사용자 지정 범위', from: '시작', to: '종료', customStart: '사용자 지정 시작일', customEnd: '사용자 지정 종료일', cancel: '취소', apply: '적용',
    equipment: '장비', work_order: '작업 지시', inventory_item: '재고 품목', preventative_maintenance: '예방 정비 점검표', organization_member: '조직 구성원', team_member: '팀 구성원', team: '팀', pm_template: '예방 정비 템플릿', INSERT: '생성됨', UPDATE: '업데이트됨', DELETE: '삭제됨',
    download: '다운로드', downloadAudit: '감사 로그 다운로드', exportRestricted: '조직 소유자와 관리자만 내보낼 수 있습니다', exportFormat: '내보내기 형식', csvDescription: '쉼표로 구분된 값', jsonDescription: '구조화된 데이터 형식',
  } },
} as const;
