export const authFlowResources = {
  en: { authFlow: {
    sessionExpiring: 'Session expiring soon', inactivityOne: 'You have been inactive. For security, you will be signed out in {{count}} second unless you continue your session.', inactivityMany: 'You have been inactive. For security, you will be signed out in {{count}} seconds unless you continue your session.', staySignedIn: 'Stay signed in', signOutNow: 'Sign out now',
    enrollFailed: 'Failed to start MFA enrollment. Please try again.', copyFailed: 'Failed to copy to clipboard', verificationFailed: 'Verification Failed', invalidCode: 'Invalid code. Please try again.', enabled: 'MFA Enabled', enabledDescription: 'Two-factor authentication has been set up successfully.',
    settingUpLabel: 'Setting up two-factor authentication', settingUp: 'Setting up authenticator...', setupTitle: 'Set Up Two-Factor Authentication', requiredDescription: 'Your role requires two-factor authentication for security.', optionalDescription: 'Add an extra layer of security to your account.', qrAlt: 'QR code for authenticator app setup — scan with Google Authenticator, Authy, or similar', manualCode: "Can't scan? Enter this code manually:", copySecret: 'Copy secret to clipboard', scanned: "I've Scanned the Code", enterCode: 'Enter the 6-digit code from your authenticator app to confirm setup', verificationCode: 'Verification code', back: 'Back', verifyingCode: 'Verifying code', verifyEnable: 'Verify & Enable', skip: 'Skip for now',
    checkingSecurity: 'Checking security requirements', verifyingSecurity: 'Verifying security requirements...', checkingAuth: 'Checking authentication', verifyingProtected: 'Verifying access before opening protected content.', checkingOnboarding: 'Checking onboarding status', checkingWorkspace: 'Checking workspace access',
    workspaceVerifyTitle: 'Unable to verify workspace access', workspacePendingTitle: 'Workspace access pending', workspaceRequiredTitle: 'Workspace access required', workspaceVerifyDescription: 'EquipQR could not confirm your Google Workspace access status.', claimedDomainDescription: 'Your Google account uses the claimed domain {{domain}}.', workspaceDomainDescription: 'Your Google Workspace domain is managed by an existing EquipQR organization.', accessCheckFailed: 'Access check failed', awaitingApproval: 'Waiting for administrator approval', noAccessYet: 'You do not have access yet', workspaceRetryHelp: 'We could not load your workspace onboarding status. Try again, or sign out and back in if the problem continues.', workspacePendingHelp: 'An organization administrator has started adding you, or you have a pending invitation. Sign in again after your administrator completes the import or your invitation is ready.', workspaceBlockedHelp: 'EquipQR does not allow automatic self-join for claimed Google Workspace domains. Ask your organization administrator to import you from Google Workspace or send you a standard EquipQR invitation.', tryAgain: 'Try again',
    devQuickLogin: 'Dev Quick Login', selectTestAccount: 'Select a test account', selectTestAccountPlaceholder: 'Select a test account...', authFailed: 'Authentication failed. Please try again.', loggingInAs: 'Logging in as', signingIn: 'Signing in...', quickLogin: 'Quick Login', premium: 'Premium', freeTier: 'Free Tier', onboarding: 'Onboarding', multiOrgTesting: 'Multi-Org Testing', invitationSignup: 'Invitation Signup (E2E)', roleOwner: 'Owner', roleAdmin: 'Admin', roleTechnician: 'Technician', roleViewer: 'Viewer', roleMember: 'Member',
  } },
  vi: { authFlow: {
    sessionExpiring: 'Phiên sắp hết hạn', inactivityOne: 'Bạn đã không hoạt động. Để bảo mật, bạn sẽ bị đăng xuất sau {{count}} giây nếu không tiếp tục phiên.', inactivityMany: 'Bạn đã không hoạt động. Để bảo mật, bạn sẽ bị đăng xuất sau {{count}} giây nếu không tiếp tục phiên.', staySignedIn: 'Tiếp tục đăng nhập', signOutNow: 'Đăng xuất ngay',
    enrollFailed: 'Không thể bắt đầu thiết lập MFA. Vui lòng thử lại.', copyFailed: 'Không thể sao chép vào bộ nhớ tạm', verificationFailed: 'Xác minh thất bại', invalidCode: 'Mã không hợp lệ. Vui lòng thử lại.', enabled: 'Đã bật MFA', enabledDescription: 'Đã thiết lập xác thực hai bước thành công.',
    settingUpLabel: 'Đang thiết lập xác thực hai bước', settingUp: 'Đang thiết lập ứng dụng xác thực...', setupTitle: 'Thiết lập xác thực hai bước', requiredDescription: 'Vai trò của bạn yêu cầu xác thực hai bước để bảo mật.', optionalDescription: 'Tăng cường bảo mật cho tài khoản của bạn.', qrAlt: 'Mã QR để thiết lập ứng dụng xác thực — quét bằng Google Authenticator, Authy hoặc ứng dụng tương tự', manualCode: 'Không quét được? Hãy nhập mã này theo cách thủ công:', copySecret: 'Sao chép khóa bí mật', scanned: 'Tôi đã quét mã', enterCode: 'Nhập mã 6 chữ số từ ứng dụng xác thực để xác nhận thiết lập', verificationCode: 'Mã xác minh', back: 'Quay lại', verifyingCode: 'Đang xác minh mã', verifyEnable: 'Xác minh và bật', skip: 'Bỏ qua lúc này',
    checkingSecurity: 'Đang kiểm tra yêu cầu bảo mật', verifyingSecurity: 'Đang xác minh yêu cầu bảo mật...', checkingAuth: 'Đang kiểm tra xác thực', verifyingProtected: 'Đang xác minh quyền truy cập trước khi mở nội dung được bảo vệ.', checkingOnboarding: 'Đang kiểm tra trạng thái giới thiệu', checkingWorkspace: 'Đang kiểm tra quyền truy cập không gian làm việc',
    workspaceVerifyTitle: 'Không thể xác minh quyền truy cập không gian làm việc', workspacePendingTitle: 'Đang chờ quyền truy cập không gian làm việc', workspaceRequiredTitle: 'Cần quyền truy cập không gian làm việc', workspaceVerifyDescription: 'EquipQR không thể xác nhận trạng thái truy cập Google Workspace của bạn.', claimedDomainDescription: 'Tài khoản Google của bạn sử dụng miền {{domain}} đã được xác nhận.', workspaceDomainDescription: 'Miền Google Workspace của bạn do một tổ chức EquipQR hiện có quản lý.', accessCheckFailed: 'Kiểm tra quyền truy cập thất bại', awaitingApproval: 'Đang chờ quản trị viên phê duyệt', noAccessYet: 'Bạn chưa có quyền truy cập', workspaceRetryHelp: 'Không thể tải trạng thái tham gia không gian làm việc. Hãy thử lại, hoặc đăng xuất rồi đăng nhập lại nếu vẫn gặp sự cố.', workspacePendingHelp: 'Quản trị viên đang thêm bạn hoặc bạn có lời mời đang chờ. Hãy đăng nhập lại sau khi quản trị viên hoàn tất nhập tài khoản hoặc lời mời sẵn sàng.', workspaceBlockedHelp: 'EquipQR không cho phép tự động tham gia các miền Google Workspace đã được xác nhận. Hãy nhờ quản trị viên nhập tài khoản từ Google Workspace hoặc gửi lời mời EquipQR thông thường.', tryAgain: 'Thử lại',
    devQuickLogin: 'Đăng nhập nhanh cho phát triển', selectTestAccount: 'Chọn tài khoản thử nghiệm', selectTestAccountPlaceholder: 'Chọn tài khoản thử nghiệm...', authFailed: 'Xác thực thất bại. Vui lòng thử lại.', loggingInAs: 'Đang đăng nhập bằng', signingIn: 'Đang đăng nhập...', quickLogin: 'Đăng nhập nhanh', premium: 'Cao cấp', freeTier: 'Gói miễn phí', onboarding: 'Giới thiệu', multiOrgTesting: 'Thử nghiệm nhiều tổ chức', invitationSignup: 'Đăng ký qua lời mời (E2E)', roleOwner: 'Chủ sở hữu', roleAdmin: 'Quản trị viên', roleTechnician: 'Kỹ thuật viên', roleViewer: 'Người xem', roleMember: 'Thành viên',
  } },
  ko: { authFlow: {
    sessionExpiring: '세션이 곧 만료됩니다', inactivityOne: '일정 시간 활동이 없었습니다. 보안을 위해 {{count}}초 후 로그아웃됩니다. 계속하려면 세션을 연장하세요.', inactivityMany: '일정 시간 활동이 없었습니다. 보안을 위해 {{count}}초 후 로그아웃됩니다. 계속하려면 세션을 연장하세요.', staySignedIn: '로그인 상태 유지', signOutNow: '지금 로그아웃',
    enrollFailed: 'MFA 등록을 시작하지 못했습니다. 다시 시도하세요.', copyFailed: '클립보드에 복사하지 못했습니다', verificationFailed: '인증 실패', invalidCode: '코드가 올바르지 않습니다. 다시 시도하세요.', enabled: 'MFA 활성화됨', enabledDescription: '2단계 인증 설정이 완료되었습니다.',
    settingUpLabel: '2단계 인증 설정 중', settingUp: '인증 앱 설정 중...', setupTitle: '2단계 인증 설정', requiredDescription: '보안을 위해 이 역할에는 2단계 인증이 필요합니다.', optionalDescription: '계정 보안을 한층 강화하세요.', qrAlt: '인증 앱 설정용 QR 코드 — Google Authenticator, Authy 또는 유사한 앱으로 스캔하세요', manualCode: '스캔할 수 없나요? 이 코드를 직접 입력하세요:', copySecret: '비밀 키 클립보드에 복사', scanned: '코드를 스캔했습니다', enterCode: '설정을 확인하려면 인증 앱의 6자리 코드를 입력하세요', verificationCode: '인증 코드', back: '뒤로', verifyingCode: '코드 확인 중', verifyEnable: '확인하고 활성화', skip: '나중에 하기',
    checkingSecurity: '보안 요구 사항 확인 중', verifyingSecurity: '보안 요구 사항 확인 중...', checkingAuth: '인증 상태 확인 중', verifyingProtected: '보호된 콘텐츠를 열기 전에 접근 권한을 확인하고 있습니다.', checkingOnboarding: '온보딩 상태 확인 중', checkingWorkspace: '워크스페이스 접근 권한 확인 중',
    workspaceVerifyTitle: '워크스페이스 접근 권한을 확인할 수 없습니다', workspacePendingTitle: '워크스페이스 접근 승인 대기 중', workspaceRequiredTitle: '워크스페이스 접근 권한 필요', workspaceVerifyDescription: 'EquipQR에서 Google Workspace 접근 상태를 확인하지 못했습니다.', claimedDomainDescription: 'Google 계정이 등록된 도메인 {{domain}}을 사용합니다.', workspaceDomainDescription: 'Google Workspace 도메인은 기존 EquipQR 조직에서 관리합니다.', accessCheckFailed: '접근 권한 확인 실패', awaitingApproval: '관리자 승인 대기 중', noAccessYet: '아직 접근 권한이 없습니다', workspaceRetryHelp: '워크스페이스 온보딩 상태를 불러오지 못했습니다. 다시 시도하거나 문제가 계속되면 로그아웃 후 다시 로그인하세요.', workspacePendingHelp: '조직 관리자가 계정을 추가 중이거나 초대가 대기 중입니다. 관리자가 가져오기를 완료하거나 초대가 준비되면 다시 로그인하세요.', workspaceBlockedHelp: 'EquipQR에서는 등록된 Google Workspace 도메인에 자동으로 가입할 수 없습니다. 조직 관리자에게 Google Workspace에서 계정을 가져오거나 일반 EquipQR 초대를 보내 달라고 요청하세요.', tryAgain: '다시 시도',
    devQuickLogin: '개발용 빠른 로그인', selectTestAccount: '테스트 계정 선택', selectTestAccountPlaceholder: '테스트 계정 선택...', authFailed: '인증에 실패했습니다. 다시 시도하세요.', loggingInAs: '로그인 계정:', signingIn: '로그인 중...', quickLogin: '빠른 로그인', premium: '프리미엄', freeTier: '무료 요금제', onboarding: '온보딩', multiOrgTesting: '다중 조직 테스트', invitationSignup: '초대 가입 (E2E)', roleOwner: '소유자', roleAdmin: '관리자', roleTechnician: '기술자', roleViewer: '조회자', roleMember: '구성원',
  } },
} as const;
