export const dashboardWidgetResources = {
  en: { dashboardWidget: {
    compliant:'Compliant', workOrdersCount:'{{count}} work orders ({{percentage}}%)', pmChartLabel:'Preventive maintenance compliance distribution chart', pmMobileSummary:'{{percentage}}% compliant · tap a row for work orders', pmSummary:'PM compliance summary: {{summary}}.', noPmData:'No PM data', noPmDataDescription:'Create PM templates or work orders to track compliance trends.', intervalTracking:'Interval Tracking ({{count}} equipment)', explainIntervalTracking:'Explain interval tracking', intervalTrackingHelp:'Equipment with hour or mileage-based PM schedules. Equipment without interval tracking typically follows date-based PM schedules.', current:'Current', dueSoon:'Due Soon', overdue:'Overdue', dateBasedTracking:'{{count}} equipment use date-based tracking.', total:'Total', equipmentCount:'{{count}} equipment ({{percentage}}%)', equipmentChartLabel:'Equipment status distribution chart', assetsTapFilter:'{{count}} assets · tap a row to filter', equipmentSummary:'Equipment status summary: {{summary}}.', noEquipmentYet:'No equipment yet', noEquipmentYetDescription:'Add equipment to see a status breakdown here.', overdueByDays:'Overdue by {{count}} day', overdueByDaysPlural:'Overdue by {{count}} days', highPriorityAria:'High priority: {{title}}', highPriorityAriaOverdue:'High priority: {{title}} — {{overdue}}', highPriorityRequires:'{{count}} work orders require immediate attention', created:'Created', due:'Due',
    fleetEfficiencyTitle:'Fleet Efficiency', fleetEfficiencyDescription:'Team equipment count versus active work orders', fleetEfficiencyAria:'Fleet efficiency scatter plot showing {{count}} teams. X-axis: total equipment count, Y-axis: active work orders.', totalEquipment:'Total Equipment', equipmentCountAxis:'Equipment Count', activeWorkOrders:'Active Work Orders', fleetSize:'Fleet Size', teamsAtPoint:'{{count}} teams at this point', clickSeeTeams:'Click to see all teams', equipmentValue:'Equipment: {{count}}', activeWorkOrdersValue:'Active work orders: {{count}}', viewEquipment:'View equipment', viewWorkOrders:'View work orders', equipment:'Equipment', noFleetEfficiencyData:'No fleet efficiency data', noFleetEfficiencyDataDescription:'Teams with equipment will appear here once they have assigned assets.',
    costTrendTitle:'Cost Trend', costTrendDescription:'Work order costs over time', week:'Week', month:'Month', totalCost:'Total Cost', noCostData:'No cost data', noCostDataDescription:'Costs will appear when work orders have recorded expenses.', thisWeek:'this week'
  } },
  vi: { dashboardWidget: {
    compliant:'Tuân thủ', workOrdersCount:'{{count}} lệnh công việc ({{percentage}}%)', pmChartLabel:'Biểu đồ phân bố mức tuân thủ bảo trì phòng ngừa', pmMobileSummary:'{{percentage}}% tuân thủ · chạm vào một dòng để xem lệnh công việc', pmSummary:'Tóm tắt tuân thủ PM: {{summary}}.', noPmData:'Chưa có dữ liệu PM', noPmDataDescription:'Tạo mẫu PM hoặc lệnh công việc để theo dõi xu hướng tuân thủ.', intervalTracking:'Theo dõi theo chu kỳ ({{count}} thiết bị)', explainIntervalTracking:'Giải thích theo dõi theo chu kỳ', intervalTrackingHelp:'Thiết bị có lịch PM dựa trên số giờ hoặc quãng đường. Thiết bị không theo dõi theo chu kỳ thường dùng lịch PM theo ngày.', current:'Hiện tại', dueSoon:'Sắp đến hạn', overdue:'Quá hạn', dateBasedTracking:'{{count}} thiết bị sử dụng theo dõi theo ngày.', total:'Tổng', equipmentCount:'{{count}} thiết bị ({{percentage}}%)', equipmentChartLabel:'Biểu đồ phân bố trạng thái thiết bị', assetsTapFilter:'{{count}} thiết bị · chạm vào một dòng để lọc', equipmentSummary:'Tóm tắt trạng thái thiết bị: {{summary}}.', noEquipmentYet:'Chưa có thiết bị', noEquipmentYetDescription:'Thêm thiết bị để xem phân bố trạng thái tại đây.', overdueByDays:'Quá hạn {{count}} ngày', overdueByDaysPlural:'Quá hạn {{count}} ngày', highPriorityAria:'Ưu tiên cao: {{title}}', highPriorityAriaOverdue:'Ưu tiên cao: {{title}} — {{overdue}}', highPriorityRequires:'{{count}} lệnh công việc cần được xử lý ngay', created:'Tạo', due:'Hạn',
    fleetEfficiencyTitle:'Hiệu suất đội thiết bị', fleetEfficiencyDescription:'Số thiết bị của nhóm so với lệnh công việc đang hoạt động', fleetEfficiencyAria:'Biểu đồ phân tán hiệu suất đội thiết bị với {{count}} nhóm. Trục X: tổng số thiết bị, trục Y: lệnh công việc đang hoạt động.', totalEquipment:'Tổng thiết bị', equipmentCountAxis:'Số lượng thiết bị', activeWorkOrders:'Lệnh công việc đang hoạt động', fleetSize:'Quy mô đội thiết bị', teamsAtPoint:'{{count}} nhóm tại điểm này', clickSeeTeams:'Nhấp để xem tất cả nhóm', equipmentValue:'Thiết bị: {{count}}', activeWorkOrdersValue:'Lệnh công việc đang hoạt động: {{count}}', viewEquipment:'Xem thiết bị', viewWorkOrders:'Xem lệnh công việc', equipment:'Thiết bị', noFleetEfficiencyData:'Chưa có dữ liệu hiệu suất đội thiết bị', noFleetEfficiencyDataDescription:'Các nhóm có thiết bị sẽ xuất hiện tại đây sau khi được gán tài sản.',
    costTrendTitle:'Xu hướng chi phí', costTrendDescription:'Chi phí lệnh công việc theo thời gian', week:'Tuần', month:'Tháng', totalCost:'Tổng chi phí', noCostData:'Chưa có dữ liệu chi phí', noCostDataDescription:'Chi phí sẽ xuất hiện khi lệnh công việc có ghi nhận chi phí.', thisWeek:'tuần này'
  } },
  ko: { dashboardWidget: {
    compliant:'준수', workOrdersCount:'작업 지시 {{count}}건 ({{percentage}}%)', pmChartLabel:'예방정비 준수 현황 분포 차트', pmMobileSummary:'준수율 {{percentage}}% · 행을 눌러 작업 지시 보기', pmSummary:'PM 준수 요약: {{summary}}.', noPmData:'PM 데이터 없음', noPmDataDescription:'PM 템플릿 또는 작업 지시를 만들어 준수 추이를 확인하세요.', intervalTracking:'주기 추적 (설비 {{count}}대)', explainIntervalTracking:'주기 추적 설명', intervalTrackingHelp:'시간 또는 주행거리 기준 PM 일정이 있는 설비입니다. 주기 추적을 사용하지 않는 설비는 일반적으로 날짜 기준 PM 일정을 사용합니다.', current:'정상', dueSoon:'곧 도래', overdue:'기한 초과', dateBasedTracking:'설비 {{count}}대가 날짜 기준 추적을 사용합니다.', total:'전체', equipmentCount:'설비 {{count}}대 ({{percentage}}%)', equipmentChartLabel:'설비 상태 분포 차트', assetsTapFilter:'설비 {{count}}대 · 행을 눌러 필터링', equipmentSummary:'설비 상태 요약: {{summary}}.', noEquipmentYet:'설비 없음', noEquipmentYetDescription:'설비를 추가하면 상태 분포를 확인할 수 있습니다.', overdueByDays:'{{count}}일 기한 초과', overdueByDaysPlural:'{{count}}일 기한 초과', highPriorityAria:'높은 우선순위: {{title}}', highPriorityAriaOverdue:'높은 우선순위: {{title}} — {{overdue}}', highPriorityRequires:'작업 지시 {{count}}건을 즉시 처리해야 합니다', created:'생성', due:'기한',
    fleetEfficiencyTitle:'설비 운영 효율', fleetEfficiencyDescription:'팀별 설비 수와 진행 중 작업 지시 비교', fleetEfficiencyAria:'{{count}}개 팀을 표시하는 설비 운영 효율 산점도입니다. X축: 전체 설비 수, Y축: 진행 중 작업 지시.', totalEquipment:'전체 설비', equipmentCountAxis:'설비 수', activeWorkOrders:'진행 중 작업 지시', fleetSize:'설비 규모', teamsAtPoint:'이 지점에 {{count}}개 팀', clickSeeTeams:'클릭하여 모든 팀 보기', equipmentValue:'설비: {{count}}대', activeWorkOrdersValue:'진행 중 작업 지시: {{count}}건', viewEquipment:'설비 보기', viewWorkOrders:'작업 지시 보기', equipment:'설비', noFleetEfficiencyData:'설비 운영 효율 데이터 없음', noFleetEfficiencyDataDescription:'설비가 배정된 팀이 여기에 표시됩니다.',
    costTrendTitle:'비용 추이', costTrendDescription:'기간별 작업 지시 비용', week:'주', month:'월', totalCost:'총 비용', noCostData:'비용 데이터 없음', noCostDataDescription:'작업 지시에 비용이 기록되면 여기에 표시됩니다.', thisWeek:'이번 주'
  } },
} as const;
