export const equipmentImportStepResources = {
  en: { equipmentImportStep: {
    uploadInfo:'Upload a CSV file with equipment data. Maximum 10,000 rows and 5MB file size. The CSV should include columns for manufacturer, model, serial number, and any custom attributes.', uploadTitle:'Upload CSV File', dragDrop:'Drag and drop your CSV file here, or click to browse', chooseFile:'Choose File', size:'Size', rows:'Rows', delimiter:'Delimiter', requirements:'Requirements:', reqHeader:'CSV format with header row', reqRows:'Maximum 10,000 data rows', reqSize:'Maximum 5MB file size', reqIdentity:'Include manufacturer, model, or serial number for equipment identification', reqDates:'Dates should be in YYYY-MM-DD, MM/DD/YYYY, or YYYY/MM/DD format',
    mappingInfo:'Map your CSV columns to equipment fields. Standard fields (manufacturer, model, serial) will be used for matching existing equipment. All other columns will be stored as custom attributes.', teamAssignment:'Team Assignment', assignTeam:'Assign new equipment to team (optional)', selectTeam:'Select team...', noTeam:'No team assignment', teamHint:'Only newly created equipment will be assigned to this team. Existing equipment team assignments will not be changed.', columnMapping:'Column Mapping', duplicate:'duplicate', duplicateHint:'Multiple columns normalize to the same key. Leftmost non-empty value per row will be used.', name:'Name', manufacturer:'Manufacturer', model:'Model', serialNumber:'Serial Number', location:'Location', lastMaintenance:'Last Maintenance', customAttribute:'Custom Attribute', skipColumn:'Skip Column', duplicateDetected:'Duplicate column mappings detected:', leftmost:'Leftmost non-empty value will be used per row.', back:'Back', previewImport:'Preview Import',
    validating:'Validating import data...', create:'Create', merge:'Merge', error:'Error', willCreate:'Will Create', willMerge:'Will Merge', errors:'Errors', validRows:'Valid Rows', warnings:'Warnings:', rowsHaveErrors:'{{count}} rows have errors and will be skipped:', rowError:'Row {{row}}: {{reason}}', moreErrors:'... and {{count}} more errors', downloadErrorReport:'Download Error Report', previewFirst:'Preview (First 20 rows)', action:'Action', serial:'Serial', customAttributes:'Custom Attributes', notes:'Notes', attributes:'{{count}} attributes', importProgress:'Import Progress', processing:'Processing equipment records...', importing:'Importing...', startImport:'Start Import',
    complete:'Import Complete!', completeDescription:'Equipment has been successfully imported to {{organization}}', processed:'Successfully processed:', failed:'Failed:', importId:'Import ID: {{id}}', teamSelected:'Team: Assigned to selected team', someFailed:'Some items failed to import', someFailedDescription:"{{count}} items couldn't be processed. Download the error report to see details.", downloadErrors:'Download Errors', close:'Close'
  }},
  vi: { equipmentImportStep: {
    uploadInfo:'Tải lên tệp CSV chứa dữ liệu thiết bị. Tối đa 10.000 dòng và dung lượng 5MB. CSV nên có các cột nhà sản xuất, model, số serial và các thuộc tính tùy chỉnh.', uploadTitle:'Tải tệp CSV', dragDrop:'Kéo thả tệp CSV vào đây hoặc bấm để chọn tệp', chooseFile:'Chọn tệp', size:'Kích thước', rows:'Số dòng', delimiter:'Dấu phân cách', requirements:'Yêu cầu:', reqHeader:'Định dạng CSV có dòng tiêu đề', reqRows:'Tối đa 10.000 dòng dữ liệu', reqSize:'Dung lượng tối đa 5MB', reqIdentity:'Có nhà sản xuất, model hoặc số serial để nhận diện thiết bị', reqDates:'Ngày theo định dạng YYYY-MM-DD, MM/DD/YYYY hoặc YYYY/MM/DD',
    mappingInfo:'Ánh xạ các cột CSV sang trường thiết bị. Các trường chuẩn (nhà sản xuất, model, serial) dùng để đối chiếu thiết bị hiện có. Các cột khác sẽ được lưu thành thuộc tính tùy chỉnh.', teamAssignment:'Gán nhóm', assignTeam:'Gán thiết bị mới vào nhóm (không bắt buộc)', selectTeam:'Chọn nhóm...', noTeam:'Không gán nhóm', teamHint:'Chỉ thiết bị mới tạo mới được gán vào nhóm này. Thiết bị hiện có sẽ không bị thay đổi nhóm.', columnMapping:'Ánh xạ cột', duplicate:'trùng', duplicateHint:'Nhiều cột được chuẩn hóa về cùng một khóa. Giá trị không rỗng bên trái nhất của mỗi dòng sẽ được dùng.', name:'Tên', manufacturer:'Nhà sản xuất', model:'Model', serialNumber:'Số serial', location:'Vị trí', lastMaintenance:'Bảo trì gần nhất', customAttribute:'Thuộc tính tùy chỉnh', skipColumn:'Bỏ qua cột', duplicateDetected:'Phát hiện ánh xạ cột trùng:', leftmost:'Giá trị không rỗng bên trái nhất sẽ được dùng cho mỗi dòng.', back:'Quay lại', previewImport:'Xem trước dữ liệu nhập',
    validating:'Đang xác thực dữ liệu nhập...', create:'Tạo mới', merge:'Gộp', error:'Lỗi', willCreate:'Sẽ tạo mới', willMerge:'Sẽ gộp', errors:'Lỗi', validRows:'Dòng hợp lệ', warnings:'Cảnh báo:', rowsHaveErrors:'{{count}} dòng có lỗi và sẽ bị bỏ qua:', rowError:'Dòng {{row}}: {{reason}}', moreErrors:'... và thêm {{count}} lỗi', downloadErrorReport:'Tải báo cáo lỗi', previewFirst:'Xem trước (20 dòng đầu)', action:'Thao tác', serial:'Serial', customAttributes:'Thuộc tính tùy chỉnh', notes:'Ghi chú', attributes:'{{count}} thuộc tính', importProgress:'Tiến độ nhập', processing:'Đang xử lý bản ghi thiết bị...', importing:'Đang nhập...', startImport:'Bắt đầu nhập',
    complete:'Nhập dữ liệu hoàn tất!', completeDescription:'Thiết bị đã được nhập thành công vào {{organization}}', processed:'Đã xử lý thành công:', failed:'Thất bại:', importId:'Mã lần nhập: {{id}}', teamSelected:'Nhóm: Đã gán vào nhóm được chọn', someFailed:'Một số mục nhập thất bại', someFailedDescription:'Không thể xử lý {{count}} mục. Tải báo cáo lỗi để xem chi tiết.', downloadErrors:'Tải lỗi', close:'Đóng'
  }},
  ko: { equipmentImportStep: {
    uploadInfo:'설비 데이터가 포함된 CSV 파일을 업로드하세요. 최대 10,000행, 5MB까지 지원합니다. 제조사, 모델, 일련번호 및 사용자 정의 속성 열을 포함하는 것을 권장합니다.', uploadTitle:'CSV 파일 업로드', dragDrop:'CSV 파일을 끌어 놓거나 클릭하여 선택하세요', chooseFile:'파일 선택', size:'크기', rows:'행', delimiter:'구분자', requirements:'요구사항:', reqHeader:'헤더 행이 있는 CSV 형식', reqRows:'최대 10,000개 데이터 행', reqSize:'최대 5MB 파일 크기', reqIdentity:'설비 식별을 위해 제조사, 모델 또는 일련번호 포함', reqDates:'날짜는 YYYY-MM-DD, MM/DD/YYYY 또는 YYYY/MM/DD 형식',
    mappingInfo:'CSV 열을 설비 필드에 매핑하세요. 표준 필드(제조사, 모델, 일련번호)는 기존 설비 매칭에 사용되며 나머지 열은 사용자 정의 속성으로 저장됩니다.', teamAssignment:'팀 지정', assignTeam:'새 설비를 팀에 지정 (선택)', selectTeam:'팀 선택...', noTeam:'팀 지정 안 함', teamHint:'새로 생성되는 설비만 이 팀에 지정됩니다. 기존 설비의 팀 지정은 변경되지 않습니다.', columnMapping:'열 매핑', duplicate:'중복', duplicateHint:'여러 열이 동일한 키로 정규화됩니다. 각 행에서 가장 왼쪽의 비어 있지 않은 값을 사용합니다.', name:'이름', manufacturer:'제조사', model:'모델', serialNumber:'일련번호', location:'위치', lastMaintenance:'최근 정비', customAttribute:'사용자 정의 속성', skipColumn:'열 건너뛰기', duplicateDetected:'중복 열 매핑 감지:', leftmost:'각 행에서 가장 왼쪽의 비어 있지 않은 값을 사용합니다.', back:'뒤로', previewImport:'가져오기 미리보기',
    validating:'가져오기 데이터 검증 중...', create:'생성', merge:'병합', error:'오류', willCreate:'생성 예정', willMerge:'병합 예정', errors:'오류', validRows:'유효한 행', warnings:'경고:', rowsHaveErrors:'{{count}}개 행에 오류가 있어 건너뜁니다:', rowError:'{{row}}행: {{reason}}', moreErrors:'... 외 {{count}}개 오류', downloadErrorReport:'오류 보고서 다운로드', previewFirst:'미리보기 (처음 20행)', action:'작업', serial:'일련번호', customAttributes:'사용자 정의 속성', notes:'메모', attributes:'속성 {{count}}개', importProgress:'가져오기 진행률', processing:'설비 레코드 처리 중...', importing:'가져오는 중...', startImport:'가져오기 시작',
    complete:'가져오기 완료!', completeDescription:'설비가 {{organization}}에 성공적으로 추가되었습니다', processed:'성공 처리:', failed:'실패:', importId:'가져오기 ID: {{id}}', teamSelected:'팀: 선택한 팀에 지정됨', someFailed:'일부 항목 가져오기 실패', someFailedDescription:'{{count}}개 항목을 처리하지 못했습니다. 자세한 내용은 오류 보고서를 다운로드하세요.', downloadErrors:'오류 다운로드', close:'닫기'
  }}
} as const;
