export const equipmentDetailsResources = {
  en: {
    equipmentDetails: {
      customAttributes: 'Custom Attributes', organizationIdRequired: 'Organization ID required', displayImageUpdated: 'Display image updated', displayImageUpdateFailed: 'Failed to update display image', unknownEquipment: 'Unknown Equipment',
      lifecycleTitle: 'Lifecycle & Warranty', installationDate: 'Installation Date', installationDatePlaceholder: 'Select installation date', editInstallationDate: 'Edit installation date', warrantyExpiration: 'Warranty Expiration', warrantyExpirationPlaceholder: 'Select warranty expiration date', editWarrantyExpiration: 'Edit warranty expiration', lastMaintenance: 'Last Maintenance', lastMaintenancePlaceholder: 'Select last maintenance date', editLastMaintenance: 'Edit last maintenance', viewLastMaintenanceWorkOrder: 'View work order for last maintenance', createdDate: 'Created Date',
      basicInformation: 'Basic Information', name: 'Name', namePlaceholder: 'Enter equipment name', editName: 'Edit name', status: 'Status', editStatus: 'Edit status', active: 'Active', maintenance: 'Maintenance', inactive: 'Inactive', workingHours: 'Working Hours', hoursValue: '{{count}} hours', assignedTeam: 'Assigned Team', selectTeam: 'Select team', editAssignedTeam: 'Edit assigned team', description: 'Description', descriptionPlaceholder: 'Enter equipment description', editDescription: 'Edit description', showDescription: 'Show description', hideDescription: 'Hide description', manufacturer: 'Manufacturer', manufacturerPlaceholder: 'Enter manufacturer', editManufacturer: 'Edit manufacturer', model: 'Model', modelPlaceholder: 'Enter model', editModel: 'Edit model', serialNumber: 'Serial Number', serialNumberPlaceholder: 'Enter serial number', editSerialNumber: 'Edit serial number',
      maintenanceInformation: 'Maintenance Information', notes: 'Notes', maintenanceNotesPlaceholder: 'Enter maintenance notes or additional information', editNotes: 'Edit notes',
      workingHoursTimeline: 'Working Hours Timeline', trackRuntime: 'Track and manage runtime for {{name}}', currentHours: 'Current Hours', updateHours: 'Update Hours', newTotalHours: 'New Total Hours', enterTotalHours: 'Enter total hours', notesOptional: 'Notes (Optional)', updateNotesPlaceholder: 'Add any notes about this update', updating: 'Updating...', cancel: 'Cancel', history: 'History', noWorkingHoursHistory: 'No working hours history found.', invalidHours: 'Please enter a valid number of hours', date: 'Date', source: 'Source', updatedBy: 'Updated By', hoursChange: 'Hours Change', unknown: 'Unknown', sourceWorkOrder: 'Work Order', sourceManual: 'Manual',
    },
  },
  vi: {
    equipmentDetails: {
      customAttributes: 'Thuộc tính tùy chỉnh', organizationIdRequired: 'Cần có mã tổ chức', displayImageUpdated: 'Đã cập nhật ảnh đại diện', displayImageUpdateFailed: 'Không thể cập nhật ảnh đại diện', unknownEquipment: 'Thiết bị chưa xác định',
      lifecycleTitle: 'Vòng đời & Bảo hành', installationDate: 'Ngày lắp đặt', installationDatePlaceholder: 'Chọn ngày lắp đặt', editInstallationDate: 'Chỉnh sửa ngày lắp đặt', warrantyExpiration: 'Ngày hết hạn bảo hành', warrantyExpirationPlaceholder: 'Chọn ngày hết hạn bảo hành', editWarrantyExpiration: 'Chỉnh sửa ngày hết hạn bảo hành', lastMaintenance: 'Bảo trì gần nhất', lastMaintenancePlaceholder: 'Chọn ngày bảo trì gần nhất', editLastMaintenance: 'Chỉnh sửa ngày bảo trì gần nhất', viewLastMaintenanceWorkOrder: 'Xem lệnh công việc của lần bảo trì gần nhất', createdDate: 'Ngày tạo',
      basicInformation: 'Thông tin cơ bản', name: 'Tên', namePlaceholder: 'Nhập tên thiết bị', editName: 'Chỉnh sửa tên', status: 'Trạng thái', editStatus: 'Chỉnh sửa trạng thái', active: 'Hoạt động', maintenance: 'Bảo trì', inactive: 'Ngừng hoạt động', workingHours: 'Giờ hoạt động', hoursValue: '{{count}} giờ', assignedTeam: 'Nhóm được gán', selectTeam: 'Chọn nhóm', editAssignedTeam: 'Chỉnh sửa nhóm được gán', description: 'Mô tả', descriptionPlaceholder: 'Nhập mô tả thiết bị', editDescription: 'Chỉnh sửa mô tả', showDescription: 'Hiện mô tả', hideDescription: 'Ẩn mô tả', manufacturer: 'Nhà sản xuất', manufacturerPlaceholder: 'Nhập nhà sản xuất', editManufacturer: 'Chỉnh sửa nhà sản xuất', model: 'Model', modelPlaceholder: 'Nhập model', editModel: 'Chỉnh sửa model', serialNumber: 'Số serial', serialNumberPlaceholder: 'Nhập số serial', editSerialNumber: 'Chỉnh sửa số serial',
      maintenanceInformation: 'Thông tin bảo trì', notes: 'Ghi chú', maintenanceNotesPlaceholder: 'Nhập ghi chú bảo trì hoặc thông tin bổ sung', editNotes: 'Chỉnh sửa ghi chú',
      workingHoursTimeline: 'Lịch sử giờ hoạt động', trackRuntime: 'Theo dõi và quản lý thời gian vận hành của {{name}}', currentHours: 'Giờ hiện tại', updateHours: 'Cập nhật giờ', newTotalHours: 'Tổng giờ mới', enterTotalHours: 'Nhập tổng số giờ', notesOptional: 'Ghi chú (Tùy chọn)', updateNotesPlaceholder: 'Thêm ghi chú cho lần cập nhật này', updating: 'Đang cập nhật...', cancel: 'Hủy', history: 'Lịch sử', noWorkingHoursHistory: 'Chưa có lịch sử giờ hoạt động.', invalidHours: 'Vui lòng nhập số giờ hợp lệ', date: 'Ngày', source: 'Nguồn', updatedBy: 'Người cập nhật', hoursChange: 'Thay đổi giờ', unknown: 'Không xác định', sourceWorkOrder: 'Lệnh công việc', sourceManual: 'Thủ công',
    },
  },
  ko: {
    equipmentDetails: {
      customAttributes: '사용자 정의 속성', organizationIdRequired: '조직 ID가 필요합니다', displayImageUpdated: '대표 이미지를 업데이트했습니다', displayImageUpdateFailed: '대표 이미지를 업데이트하지 못했습니다', unknownEquipment: '알 수 없는 설비',
      lifecycleTitle: '수명 주기 및 보증', installationDate: '설치일', installationDatePlaceholder: '설치일 선택', editInstallationDate: '설치일 수정', warrantyExpiration: '보증 만료일', warrantyExpirationPlaceholder: '보증 만료일 선택', editWarrantyExpiration: '보증 만료일 수정', lastMaintenance: '최근 정비', lastMaintenancePlaceholder: '최근 정비일 선택', editLastMaintenance: '최근 정비일 수정', viewLastMaintenanceWorkOrder: '최근 정비 작업 지시 보기', createdDate: '생성일',
      basicInformation: '기본 정보', name: '이름', namePlaceholder: '설비 이름 입력', editName: '이름 수정', status: '상태', editStatus: '상태 수정', active: '가동 중', maintenance: '정비 중', inactive: '비활성', workingHours: '가동 시간', hoursValue: '{{count}}시간', assignedTeam: '지정 팀', selectTeam: '팀 선택', editAssignedTeam: '지정 팀 수정', description: '설명', descriptionPlaceholder: '설비 설명 입력', editDescription: '설명 수정', showDescription: '설명 표시', hideDescription: '설명 숨기기', manufacturer: '제조사', manufacturerPlaceholder: '제조사 입력', editManufacturer: '제조사 수정', model: '모델', modelPlaceholder: '모델 입력', editModel: '모델 수정', serialNumber: '일련번호', serialNumberPlaceholder: '일련번호 입력', editSerialNumber: '일련번호 수정',
      maintenanceInformation: '정비 정보', notes: '메모', maintenanceNotesPlaceholder: '정비 메모 또는 추가 정보 입력', editNotes: '메모 수정',
      workingHoursTimeline: '가동 시간 이력', trackRuntime: '{{name}}의 가동 시간을 추적하고 관리합니다', currentHours: '현재 시간', updateHours: '시간 업데이트', newTotalHours: '새 총 시간', enterTotalHours: '총 시간 입력', notesOptional: '메모 (선택)', updateNotesPlaceholder: '이번 업데이트에 대한 메모 추가', updating: '업데이트 중...', cancel: '취소', history: '이력', noWorkingHoursHistory: '가동 시간 이력이 없습니다.', invalidHours: '유효한 시간을 입력하세요', date: '날짜', source: '출처', updatedBy: '업데이트한 사람', hoursChange: '시간 변경', unknown: '알 수 없음', sourceWorkOrder: '작업 지시', sourceManual: '수동',
    },
  },
} as const;
