export const equipmentImportResources = {
  en: {
    equipmentImport: {
      title: 'Import CSV', upload: 'Upload', map: 'Map', previewImport: 'Preview & Import',
      importInProgress: 'Import in progress', importInProgressDescription: 'Please wait for the import to complete before closing.',
      fileTooLarge: 'File too large', fileTooLargeDescription: 'CSV files must be under 5MB.', parseError: 'Parse error', parseErrorDescription: 'Failed to parse CSV file. Please check the format.',
      emptyFile: 'Empty file', emptyFileDescription: 'The CSV file contains no data rows.', tooManyRows: 'Too many rows', tooManyRowsDescription: 'CSV files are limited to 10,000 rows maximum.',
      parseFailed: 'Failed to parse CSV file.', fileReadError: 'File read error', fileReadErrorDescription: 'Failed to read the CSV file.', dryRunFailed: 'Dry run failed', dryRunFailedDescription: 'Failed to validate import data. Please try again.',
      importCompleted: 'Import completed', importCompletedDescription: 'Created: {{created}}, Merged: {{merged}}, Failed: {{failed}}', importFailed: 'Import failed', importFailedDescription: 'The import process encountered an error. Please try again.', chunkFailed: 'Chunk {{chunk}} failed: {{message}}', dryRunError: 'Dry run failed',
      uploadInfo: 'Upload a CSV file with equipment data. Maximum 10,000 rows and 5MB file size. The CSV should include columns for manufacturer, model, serial number, and any custom attributes.',
      uploadCsvFile: 'Upload CSV File', dragBrowse: 'Drag and drop your CSV file here, or click to browse', chooseFile: 'Choose File', size: 'Size', rows: 'Rows', delimiter: 'Delimiter', requirements: 'Requirements:',
      requirementHeader: 'CSV format with header row', requirementRows: 'Maximum 10,000 data rows', requirementSize: 'Maximum 5MB file size', requirementIdentity: 'Include manufacturer, model, or serial number for equipment identification', requirementDates: 'Dates should be in YYYY-MM-DD, MM/DD/YYYY, or YYYY/MM/DD format',
      mappingInfo: 'Map your CSV columns to equipment fields. Standard fields (manufacturer, model, serial) will be used for matching existing equipment. All other columns will be stored as custom attributes.',
      teamAssignment: 'Team Assignment', assignNewToTeam: 'Assign new equipment to team (optional)', selectTeam: 'Select team...', noTeamAssignment: 'No team assignment', teamAssignmentHint: 'Only newly created equipment will be assigned to this team. Existing equipment team assignments will not be changed.',
      columnMapping: 'Column Mapping', duplicate: 'duplicate', duplicateTooltip: 'Multiple columns normalize to the same key. Leftmost non-empty value per row will be used.', name: 'Name', manufacturer: 'Manufacturer', model: 'Model', serialNumber: 'Serial Number', location: 'Location', lastMaintenance: 'Last Maintenance', customAttribute: 'Custom Attribute', skipColumn: 'Skip Column', duplicateMappings: 'Duplicate column mappings detected:', duplicateValueHint: 'Leftmost non-empty value will be used per row.', back: 'Back', previewImportButton: 'Preview Import',
      validating: 'Validating import data...', create: 'Create', merge: 'Merge', error: 'Error', willCreate: 'Will Create', willMerge: 'Will Merge', errors: 'Errors', validRows: 'Valid Rows', warnings: 'Warnings:', rowsSkipped: '{{count}} rows have errors and will be skipped:', rowError: 'Row {{row}}: {{reason}}', moreErrors: '... and {{count}} more errors', downloadErrorReport: 'Download Error Report', previewFirstRows: 'Preview (First 20 rows)', action: 'Action', serial: 'Serial', customAttributes: 'Custom Attributes', notes: 'Notes', attributeCount: '{{count}} attributes', importProgress: 'Import Progress', processingRecords: 'Processing equipment records...', importing: 'Importing...', startImport: 'Start Import',
      completeTitle: 'Import Complete!', completeDescription: 'Equipment has been successfully imported to {{organization}}', successfullyProcessed: 'Successfully processed:', failed: 'Failed:', importId: 'Import ID: {{id}}', assignedTeam: 'Team: Assigned to selected team', someFailed: 'Some items failed to import', someFailedDescription: "{{count}} items couldn't be processed. Download the error report to see details.", downloadErrors: 'Download Errors', close: 'Close',
    },
  },
  vi: {
    equipmentImport: {
      title: 'Nhập CSV', upload: 'Tải tệp', map: 'Ánh xạ', previewImport: 'Xem trước & Nhập', importInProgress: 'Đang nhập dữ liệu', importInProgressDescription: 'Vui lòng chờ quá trình nhập hoàn tất trước khi đóng.',
      fileTooLarge: 'Tệp quá lớn', fileTooLargeDescription: 'Tệp CSV phải nhỏ hơn 5MB.', parseError: 'Lỗi đọc CSV', parseErrorDescription: 'Không thể đọc tệp CSV. Vui lòng kiểm tra lại định dạng.', emptyFile: 'Tệp rỗng', emptyFileDescription: 'Tệp CSV không chứa dòng dữ liệu nào.', tooManyRows: 'Quá nhiều dòng', tooManyRowsDescription: 'Tệp CSV được giới hạn tối đa 10.000 dòng.', parseFailed: 'Không thể đọc tệp CSV.', fileReadError: 'Lỗi đọc tệp', fileReadErrorDescription: 'Không thể đọc tệp CSV.', dryRunFailed: 'Kiểm tra thử thất bại', dryRunFailedDescription: 'Không thể xác thực dữ liệu nhập. Vui lòng thử lại.', importCompleted: 'Đã nhập dữ liệu', importCompletedDescription: 'Đã tạo: {{created}}, Đã gộp: {{merged}}, Thất bại: {{failed}}', importFailed: 'Nhập dữ liệu thất bại', importFailedDescription: 'Quá trình nhập gặp lỗi. Vui lòng thử lại.', chunkFailed: 'Lô {{chunk}} thất bại: {{message}}', dryRunError: 'Kiểm tra thử thất bại',
      uploadInfo: 'Tải lên tệp CSV chứa dữ liệu thiết bị. Tối đa 10.000 dòng và dung lượng 5MB. CSV nên có các cột nhà sản xuất, model, số serial và các thuộc tính tùy chỉnh nếu có.', uploadCsvFile: 'Tải tệp CSV', dragBrowse: 'Kéo thả tệp CSV vào đây hoặc nhấp để chọn tệp', chooseFile: 'Chọn tệp', size: 'Dung lượng', rows: 'Số dòng', delimiter: 'Dấu phân cách', requirements: 'Yêu cầu:', requirementHeader: 'Định dạng CSV có dòng tiêu đề', requirementRows: 'Tối đa 10.000 dòng dữ liệu', requirementSize: 'Dung lượng tối đa 5MB', requirementIdentity: 'Có nhà sản xuất, model hoặc số serial để nhận diện thiết bị', requirementDates: 'Ngày theo định dạng YYYY-MM-DD, MM/DD/YYYY hoặc YYYY/MM/DD',
      mappingInfo: 'Ánh xạ các cột CSV sang trường thiết bị. Các trường chuẩn (nhà sản xuất, model, serial) được dùng để đối chiếu thiết bị hiện có. Các cột khác được lưu thành thuộc tính tùy chỉnh.', teamAssignment: 'Gán nhóm', assignNewToTeam: 'Gán thiết bị mới vào nhóm (không bắt buộc)', selectTeam: 'Chọn nhóm...', noTeamAssignment: 'Không gán nhóm', teamAssignmentHint: 'Chỉ thiết bị mới tạo mới được gán vào nhóm này. Nhóm của thiết bị hiện có sẽ không bị thay đổi.', columnMapping: 'Ánh xạ cột', duplicate: 'trùng', duplicateTooltip: 'Nhiều cột được chuẩn hóa về cùng một khóa. Hệ thống dùng giá trị không rỗng đầu tiên từ trái sang phải cho mỗi dòng.', name: 'Tên', manufacturer: 'Nhà sản xuất', model: 'Model', serialNumber: 'Số serial', location: 'Vị trí', lastMaintenance: 'Bảo trì gần nhất', customAttribute: 'Thuộc tính tùy chỉnh', skipColumn: 'Bỏ qua cột', duplicateMappings: 'Phát hiện ánh xạ cột trùng:', duplicateValueHint: 'Mỗi dòng sẽ dùng giá trị không rỗng đầu tiên từ trái sang phải.', back: 'Quay lại', previewImportButton: 'Xem trước dữ liệu nhập',
      validating: 'Đang kiểm tra dữ liệu nhập...', create: 'Tạo mới', merge: 'Gộp', error: 'Lỗi', willCreate: 'Sẽ tạo', willMerge: 'Sẽ gộp', errors: 'Lỗi', validRows: 'Dòng hợp lệ', warnings: 'Cảnh báo:', rowsSkipped: '{{count}} dòng có lỗi và sẽ bị bỏ qua:', rowError: 'Dòng {{row}}: {{reason}}', moreErrors: '... và {{count}} lỗi khác', downloadErrorReport: 'Tải báo cáo lỗi', previewFirstRows: 'Xem trước (20 dòng đầu)', action: 'Thao tác', serial: 'Serial', customAttributes: 'Thuộc tính tùy chỉnh', notes: 'Ghi chú', attributeCount: '{{count}} thuộc tính', importProgress: 'Tiến độ nhập', processingRecords: 'Đang xử lý dữ liệu thiết bị...', importing: 'Đang nhập...', startImport: 'Bắt đầu nhập',
      completeTitle: 'Nhập dữ liệu hoàn tất!', completeDescription: 'Thiết bị đã được nhập thành công vào {{organization}}', successfullyProcessed: 'Xử lý thành công:', failed: 'Thất bại:', importId: 'Mã nhập: {{id}}', assignedTeam: 'Nhóm: Đã gán vào nhóm được chọn', someFailed: 'Một số mục nhập thất bại', someFailedDescription: '{{count}} mục không thể xử lý. Hãy tải báo cáo lỗi để xem chi tiết.', downloadErrors: 'Tải lỗi', close: 'Đóng',
    },
  },
  ko: {
    equipmentImport: {
      title: 'CSV 가져오기', upload: '업로드', map: '매핑', previewImport: '미리보기 및 가져오기', importInProgress: '가져오는 중', importInProgressDescription: '가져오기가 완료될 때까지 창을 닫지 마세요.', fileTooLarge: '파일이 너무 큽니다', fileTooLargeDescription: 'CSV 파일은 5MB 미만이어야 합니다.', parseError: 'CSV 해석 오류', parseErrorDescription: 'CSV 파일을 해석하지 못했습니다. 형식을 확인하세요.', emptyFile: '빈 파일', emptyFileDescription: 'CSV 파일에 데이터 행이 없습니다.', tooManyRows: '행이 너무 많습니다', tooManyRowsDescription: 'CSV 파일은 최대 10,000행까지 지원합니다.', parseFailed: 'CSV 파일을 해석하지 못했습니다.', fileReadError: '파일 읽기 오류', fileReadErrorDescription: 'CSV 파일을 읽지 못했습니다.', dryRunFailed: '사전 검증 실패', dryRunFailedDescription: '가져오기 데이터를 검증하지 못했습니다. 다시 시도하세요.', importCompleted: '가져오기 완료', importCompletedDescription: '생성: {{created}}, 병합: {{merged}}, 실패: {{failed}}', importFailed: '가져오기 실패', importFailedDescription: '가져오기 중 오류가 발생했습니다. 다시 시도하세요.', chunkFailed: '{{chunk}}번째 묶음 실패: {{message}}', dryRunError: '사전 검증 실패',
      uploadInfo: '설비 데이터가 포함된 CSV 파일을 업로드하세요. 최대 10,000행, 파일 크기 5MB까지 지원합니다. 제조사, 모델, 일련번호 및 사용자 정의 속성 열을 포함하는 것을 권장합니다.', uploadCsvFile: 'CSV 파일 업로드', dragBrowse: 'CSV 파일을 끌어다 놓거나 클릭하여 선택하세요', chooseFile: '파일 선택', size: '크기', rows: '행', delimiter: '구분자', requirements: '요구사항:', requirementHeader: '헤더 행이 있는 CSV 형식', requirementRows: '최대 10,000개 데이터 행', requirementSize: '최대 파일 크기 5MB', requirementIdentity: '설비 식별을 위해 제조사, 모델 또는 일련번호 포함', requirementDates: '날짜 형식: YYYY-MM-DD, MM/DD/YYYY 또는 YYYY/MM/DD',
      mappingInfo: 'CSV 열을 설비 필드에 매핑하세요. 표준 필드(제조사, 모델, 일련번호)는 기존 설비 매칭에 사용되며 나머지 열은 사용자 정의 속성으로 저장됩니다.', teamAssignment: '팀 지정', assignNewToTeam: '새 설비를 팀에 지정 (선택 사항)', selectTeam: '팀 선택...', noTeamAssignment: '팀 지정 안 함', teamAssignmentHint: '새로 생성되는 설비만 이 팀에 지정됩니다. 기존 설비의 팀 지정은 변경되지 않습니다.', columnMapping: '열 매핑', duplicate: '중복', duplicateTooltip: '여러 열이 동일한 키로 정규화됩니다. 각 행에서 가장 왼쪽의 비어 있지 않은 값을 사용합니다.', name: '이름', manufacturer: '제조사', model: '모델', serialNumber: '일련번호', location: '위치', lastMaintenance: '최근 정비', customAttribute: '사용자 정의 속성', skipColumn: '열 건너뛰기', duplicateMappings: '중복 열 매핑 감지:', duplicateValueHint: '각 행에서 가장 왼쪽의 비어 있지 않은 값을 사용합니다.', back: '뒤로', previewImportButton: '가져오기 미리보기',
      validating: '가져오기 데이터 검증 중...', create: '생성', merge: '병합', error: '오류', willCreate: '생성 예정', willMerge: '병합 예정', errors: '오류', validRows: '유효 행', warnings: '경고:', rowsSkipped: '{{count}}개 행에 오류가 있어 건너뜁니다:', rowError: '{{row}}행: {{reason}}', moreErrors: '... 외 {{count}}개 오류', downloadErrorReport: '오류 보고서 다운로드', previewFirstRows: '미리보기 (처음 20행)', action: '작업', serial: '일련번호', customAttributes: '사용자 정의 속성', notes: '메모', attributeCount: '{{count}}개 속성', importProgress: '가져오기 진행률', processingRecords: '설비 레코드 처리 중...', importing: '가져오는 중...', startImport: '가져오기 시작',
      completeTitle: '가져오기 완료!', completeDescription: '{{organization}}에 설비를 성공적으로 가져왔습니다', successfullyProcessed: '성공적으로 처리됨:', failed: '실패:', importId: '가져오기 ID: {{id}}', assignedTeam: '팀: 선택한 팀에 지정됨', someFailed: '일부 항목 가져오기 실패', someFailedDescription: '{{count}}개 항목을 처리하지 못했습니다. 자세한 내용은 오류 보고서를 다운로드하세요.', downloadErrors: '오류 다운로드', close: '닫기',
    },
  },
} as const;
