export const equipmentResources = {
  en: { equipment: {
    title:'Equipment', selectOrganization:'Please select an organization to view equipment.', manageFor:'Manage equipment for {{name}}', addEquipment:'Add Equipment', addSingleEquipment:'Add Single Equipment', bulkEditGrid:'Bulk Edit (Grid)', addEquipmentAria:'Add equipment', result:'result',
    searchPlaceholder:'Search equipment...', searchAria:'Search equipment', active:'Active', status:'Status', manufacturer:'Manufacturer', location:'Location', warrantyExpiring:'Warranty Expiring', clearStatusFilter:'Clear status filter', clearManufacturerFilter:'Clear manufacturer filter', clearLocationFilter:'Clear location filter', clearWarrantyFilter:'Clear warranty expiring filter', clearAll:'Clear all',
    sortBy:'Sort by', sortDescription:'Change how equipment is sorted on this device.', sortFieldAria:'Sort equipment by field', openFilters:'Open filters', openFiltersActive:'Open filters, {{count}} active', filterEquipment:'Filter Equipment', filterDescription:'Filter equipment by status, manufacturer, or location. Team scope is set from the breadcrumb at the top of the screen.', quickFilters:'Quick filters', filters:'Filters', allStatus:'All Status', clearAllFilters:'Clear All Filters',
    noMatches:'No equipment matches your filters', noEquipmentYet:'No equipment yet', adjustFilters:'Try adjusting or clearing your search and filter criteria to see more results.', addFirstEquipment:'Get started by adding your first piece of equipment to {{name}}.', clearFilters:'Clear Filters', pendingSync:'Pending sync', pendingViewDescription:'This equipment will be available for viewing after it syncs.', pendingQrDescription:'QR codes are generated after the equipment syncs.', pendingActionDescription:'This action will be available after the equipment syncs.', showQrFor:'Show QR code for {{name}}', showQrCode:'Show QR Code', hours:'Hours', lastMaintenance:'Last maint', pmStatus:'PM status', equipmentActions:'Equipment actions', history:'History', noTableMatches:'No equipment matches your filters.',
    columns:'Columns', toggleColumns:'Toggle columns', resetColumns:'Reset to defaults', name:'Name', model:'Model', serialNumber:'Serial #', team:'Team', lastMaintenanceFull:'Last Maintenance', newWorkOrder:'New work order', workOrder:'Work Order',
    pmOverdue:'PM Overdue', pmDueSoon:'PM Due Soon', pmCurrent:'PM Current', daysOverdue:'{{count}} days overdue', hoursOverdue:'{{count}} hrs overdue', overdue:'Overdue', approachingDays:'Approaching {{count}}-day interval (80%+ used)', approachingHours:'Approaching {{count}}-hr interval (80%+ used)', withinInterval:'Within maintenance interval'
  } },
  vi: { equipment: {
    title:'Thiết bị', selectOrganization:'Vui lòng chọn một tổ chức để xem thiết bị.', manageFor:'Quản lý thiết bị cho {{name}}', addEquipment:'Thêm thiết bị', addSingleEquipment:'Thêm một thiết bị', bulkEditGrid:'Chỉnh sửa hàng loạt (Dạng lưới)', addEquipmentAria:'Thêm thiết bị', result:'kết quả',
    searchPlaceholder:'Tìm kiếm thiết bị...', searchAria:'Tìm kiếm thiết bị', active:'Đang áp dụng', status:'Trạng thái', manufacturer:'Nhà sản xuất', location:'Vị trí', warrantyExpiring:'Sắp hết bảo hành', clearStatusFilter:'Xóa bộ lọc trạng thái', clearManufacturerFilter:'Xóa bộ lọc nhà sản xuất', clearLocationFilter:'Xóa bộ lọc vị trí', clearWarrantyFilter:'Xóa bộ lọc sắp hết bảo hành', clearAll:'Xóa tất cả',
    sortBy:'Sắp xếp theo', sortDescription:'Thay đổi cách sắp xếp thiết bị trên thiết bị này.', sortFieldAria:'Sắp xếp thiết bị theo trường', openFilters:'Mở bộ lọc', openFiltersActive:'Mở bộ lọc, {{count}} đang áp dụng', filterEquipment:'Lọc thiết bị', filterDescription:'Lọc thiết bị theo trạng thái, nhà sản xuất hoặc vị trí. Phạm vi nhóm được đặt từ breadcrumb ở đầu màn hình.', quickFilters:'Bộ lọc nhanh', filters:'Bộ lọc', allStatus:'Tất cả trạng thái', clearAllFilters:'Xóa tất cả bộ lọc',
    noMatches:'Không có thiết bị nào khớp với bộ lọc', noEquipmentYet:'Chưa có thiết bị', adjustFilters:'Hãy điều chỉnh hoặc xóa tiêu chí tìm kiếm và bộ lọc để xem thêm kết quả.', addFirstEquipment:'Bắt đầu bằng cách thêm thiết bị đầu tiên vào {{name}}.', clearFilters:'Xóa bộ lọc', pendingSync:'Đang chờ đồng bộ', pendingViewDescription:'Thiết bị này sẽ có thể xem sau khi đồng bộ xong.', pendingQrDescription:'Mã QR sẽ được tạo sau khi thiết bị đồng bộ xong.', pendingActionDescription:'Thao tác này sẽ khả dụng sau khi thiết bị đồng bộ xong.', showQrFor:'Hiển thị mã QR cho {{name}}', showQrCode:'Hiển thị mã QR', hours:'Giờ hoạt động', lastMaintenance:'Bảo trì gần nhất', pmStatus:'Trạng thái PM', equipmentActions:'Thao tác thiết bị', history:'Lịch sử', noTableMatches:'Không có thiết bị nào khớp với bộ lọc.',
    columns:'Cột', toggleColumns:'Bật/tắt cột', resetColumns:'Đặt lại mặc định', name:'Tên', model:'Model', serialNumber:'Số serial', team:'Nhóm', lastMaintenanceFull:'Bảo trì gần nhất', newWorkOrder:'Lệnh công việc mới', workOrder:'Lệnh công việc',
    pmOverdue:'PM quá hạn', pmDueSoon:'PM sắp đến hạn', pmCurrent:'PM hiện tại', daysOverdue:'Quá hạn {{count}} ngày', hoursOverdue:'Quá hạn {{count}} giờ', overdue:'Quá hạn', approachingDays:'Sắp đến chu kỳ {{count}} ngày (đã dùng 80%+)', approachingHours:'Sắp đến chu kỳ {{count}} giờ (đã dùng 80%+)', withinInterval:'Đang trong chu kỳ bảo trì'
  } },
  ko: { equipment: {
    title:'설비', selectOrganization:'설비를 보려면 조직을 선택하세요.', manageFor:'{{name}}의 설비 관리', addEquipment:'설비 추가', addSingleEquipment:'설비 1대 추가', bulkEditGrid:'일괄 수정 (그리드)', addEquipmentAria:'설비 추가', result:'결과',
    searchPlaceholder:'설비 검색...', searchAria:'설비 검색', active:'적용 중', status:'상태', manufacturer:'제조사', location:'위치', warrantyExpiring:'보증 만료 임박', clearStatusFilter:'상태 필터 해제', clearManufacturerFilter:'제조사 필터 해제', clearLocationFilter:'위치 필터 해제', clearWarrantyFilter:'보증 만료 임박 필터 해제', clearAll:'모두 지우기',
    sortBy:'정렬 기준', sortDescription:'이 기기에서 설비 정렬 방식을 변경합니다.', sortFieldAria:'설비 정렬 필드', openFilters:'필터 열기', openFiltersActive:'필터 열기, {{count}}개 적용 중', filterEquipment:'설비 필터', filterDescription:'상태, 제조사 또는 위치로 설비를 필터링합니다. 팀 범위는 화면 상단의 브레드크럼에서 설정합니다.', quickFilters:'빠른 필터', filters:'필터', allStatus:'전체 상태', clearAllFilters:'모든 필터 지우기',
    noMatches:'필터와 일치하는 설비가 없습니다', noEquipmentYet:'아직 설비가 없습니다', adjustFilters:'검색 또는 필터 조건을 조정하거나 지워 더 많은 결과를 확인하세요.', addFirstEquipment:'{{name}}에 첫 설비를 추가해 시작하세요.', clearFilters:'필터 지우기', pendingSync:'동기화 대기 중', pendingViewDescription:'동기화가 완료되면 이 설비를 볼 수 있습니다.', pendingQrDescription:'설비 동기화가 완료되면 QR 코드가 생성됩니다.', pendingActionDescription:'설비 동기화가 완료되면 이 작업을 사용할 수 있습니다.', showQrFor:'{{name}}의 QR 코드 표시', showQrCode:'QR 코드 표시', hours:'가동 시간', lastMaintenance:'최근 정비', pmStatus:'PM 상태', equipmentActions:'설비 작업', history:'이력', noTableMatches:'필터와 일치하는 설비가 없습니다.',
    columns:'열', toggleColumns:'열 표시 설정', resetColumns:'기본값으로 재설정', name:'이름', model:'모델', serialNumber:'일련번호', team:'팀', lastMaintenanceFull:'최근 정비', newWorkOrder:'새 작업 지시', workOrder:'작업 지시',
    pmOverdue:'PM 기한 초과', pmDueSoon:'PM 도래 임박', pmCurrent:'PM 정상', daysOverdue:'{{count}}일 기한 초과', hoursOverdue:'{{count}}시간 기한 초과', overdue:'기한 초과', approachingDays:'{{count}}일 주기 도래 임박 (80% 이상 사용)', approachingHours:'{{count}}시간 주기 도래 임박 (80% 이상 사용)', withinInterval:'정비 주기 내'
  } },
} as const;
