export const equipmentLocationResources = {
  en: {
    equipmentLocation: {
      editAddress: 'Edit equipment address', setAddress: 'Set equipment address', useCurrentLocation: 'Use my current location', loadingMap: 'Loading map...', noCoordinates: 'No map coordinates yet', noCoordinatesEditable: 'Set an equipment address or use this device’s location.', noCoordinatesReadonly: 'Set an equipment address or current device location on the equipment page.', noLocation: 'No location set', editTeamLocation: 'Edit team location on team page', searchAddress: 'Search for an equipment address...', saving: 'Saving...', saveLocation: 'Save equipment location', cancel: 'Cancel', saveHint: 'Saving sets a dedicated equipment address, which takes priority over the team default location.', setOnEquipmentPage: 'Set location on equipment page', captureTitle: 'Set equipment location from this device', useThisLocation: 'Use this location', source: 'Location source', effective: 'Effective location', team: 'Team location', manual: 'Equipment location', scan: 'Last scan location', legacy: 'Legacy location',
      mapUnavailable: 'Map unavailable', retry: 'Retry',
      captureDefaultTitle: 'Set equipment location', captureDefaultConfirm: 'Set equipment location', captureDescription: 'Stand next to the equipment, use your device location once, then pan the map so the centered pin sits on the equipment. The pin lifts while you move the map; the shadow shows where it will land.', locationRequestNotice: 'We only request your location after you click the button below.', loadingMapPreview: 'Loading map...', mapPreviewUnavailable: 'Map preview unavailable.', selectedLocation: 'Selected location: {{lat}}, {{lng}}', adjustedOnMap: 'adjusted on map', confirmShadowHint: 'Confirm only if the shadow is where the equipment is right now.', geoUnsupported: 'Location services are not available in this browser.', geoPermissionDenied: 'Location permission was denied. Allow location access to use this feature.', geoPositionUnavailable: 'Your device location is unavailable right now.', geoTimeout: 'Timed out while waiting for your device location.', geoUnknown: 'Unable to read your device location.'
    }
  },
  vi: {
    equipmentLocation: {
      editAddress: 'Chỉnh sửa địa chỉ thiết bị', setAddress: 'Đặt địa chỉ thiết bị', useCurrentLocation: 'Dùng vị trí hiện tại của tôi', loadingMap: 'Đang tải bản đồ...', noCoordinates: 'Chưa có tọa độ bản đồ', noCoordinatesEditable: 'Hãy đặt địa chỉ thiết bị hoặc dùng vị trí của thiết bị này.', noCoordinatesReadonly: 'Hãy đặt địa chỉ thiết bị hoặc vị trí thiết bị hiện tại trên trang thiết bị.', noLocation: 'Chưa đặt vị trí', editTeamLocation: 'Chỉnh sửa vị trí nhóm trên trang nhóm', searchAddress: 'Tìm địa chỉ thiết bị...', saving: 'Đang lưu...', saveLocation: 'Lưu vị trí thiết bị', cancel: 'Hủy', saveHint: 'Khi lưu, hệ thống sẽ đặt địa chỉ riêng cho thiết bị và ưu tiên địa chỉ này hơn vị trí mặc định của nhóm.', setOnEquipmentPage: 'Đặt vị trí trên trang thiết bị', captureTitle: 'Đặt vị trí thiết bị từ thiết bị này', useThisLocation: 'Dùng vị trí này', source: 'Nguồn vị trí', effective: 'Vị trí hiệu lực', team: 'Vị trí nhóm', manual: 'Vị trí thiết bị', scan: 'Vị trí quét gần nhất', legacy: 'Vị trí cũ',
      mapUnavailable: 'Bản đồ không khả dụng', retry: 'Thử lại',
      captureDefaultTitle: 'Đặt vị trí thiết bị', captureDefaultConfirm: 'Đặt vị trí thiết bị', captureDescription: 'Đứng cạnh thiết bị, lấy vị trí của thiết bị này một lần, sau đó kéo bản đồ để ghim ở giữa nằm đúng vị trí thiết bị. Ghim sẽ nhấc lên khi bạn di chuyển bản đồ; bóng ghim cho biết vị trí sẽ được đặt.', locationRequestNotice: 'Hệ thống chỉ yêu cầu vị trí sau khi bạn nhấn nút bên dưới.', loadingMapPreview: 'Đang tải bản đồ...', mapPreviewUnavailable: 'Không thể hiển thị bản đồ xem trước.', selectedLocation: 'Vị trí đã chọn: {{lat}}, {{lng}}', adjustedOnMap: 'đã điều chỉnh trên bản đồ', confirmShadowHint: 'Chỉ xác nhận khi bóng ghim nằm đúng vị trí hiện tại của thiết bị.', geoUnsupported: 'Trình duyệt này không hỗ trợ dịch vụ vị trí.', geoPermissionDenied: 'Quyền truy cập vị trí đã bị từ chối. Hãy cho phép truy cập vị trí để dùng tính năng này.', geoPositionUnavailable: 'Hiện không thể xác định vị trí của thiết bị này.', geoTimeout: 'Hết thời gian chờ vị trí của thiết bị.', geoUnknown: 'Không thể đọc vị trí của thiết bị.'
    }
  },
  ko: {
    equipmentLocation: {
      editAddress: '설비 주소 수정', setAddress: '설비 주소 설정', useCurrentLocation: '현재 위치 사용', loadingMap: '지도 불러오는 중...', noCoordinates: '아직 지도 좌표가 없습니다', noCoordinatesEditable: '설비 주소를 설정하거나 이 기기의 위치를 사용하세요.', noCoordinatesReadonly: '설비 페이지에서 설비 주소 또는 현재 기기 위치를 설정하세요.', noLocation: '위치가 설정되지 않았습니다', editTeamLocation: '팀 페이지에서 팀 위치 수정', searchAddress: '설비 주소 검색...', saving: '저장 중...', saveLocation: '설비 위치 저장', cancel: '취소', saveHint: '저장하면 설비 전용 주소가 설정되며 팀 기본 위치보다 우선합니다.', setOnEquipmentPage: '설비 페이지에서 위치 설정', captureTitle: '이 기기에서 설비 위치 설정', useThisLocation: '이 위치 사용', source: '위치 출처', effective: '적용 위치', team: '팀 위치', manual: '설비 위치', scan: '최근 스캔 위치', legacy: '기존 위치',
      mapUnavailable: '지도를 사용할 수 없습니다', retry: '다시 시도',
      captureDefaultTitle: '설비 위치 설정', captureDefaultConfirm: '설비 위치 설정', captureDescription: '설비 옆에서 기기 위치를 한 번 가져온 다음 지도를 이동하여 중앙 핀이 설비 위치에 놓이도록 조정하세요. 지도를 움직이는 동안 핀이 올라가며 그림자가 핀이 놓일 위치를 보여 줍니다.', locationRequestNotice: '아래 버튼을 누른 뒤에만 위치를 요청합니다.', loadingMapPreview: '지도 불러오는 중...', mapPreviewUnavailable: '지도 미리보기를 사용할 수 없습니다.', selectedLocation: '선택한 위치: {{lat}}, {{lng}}', adjustedOnMap: '지도에서 조정됨', confirmShadowHint: '그림자가 현재 설비 위치에 정확히 있을 때만 확인하세요.', geoUnsupported: '이 브라우저에서는 위치 서비스를 사용할 수 없습니다.', geoPermissionDenied: '위치 권한이 거부되었습니다. 이 기능을 사용하려면 위치 접근을 허용하세요.', geoPositionUnavailable: '현재 기기 위치를 확인할 수 없습니다.', geoTimeout: '기기 위치를 기다리는 동안 시간이 초과되었습니다.', geoUnknown: '기기 위치를 읽을 수 없습니다.'
    }
  }
} as const;
