// Product messaging on Security and Right to Repair. The legal landscape and
// contract disclaimer intentionally remain in their reviewed source language.
export const marketingTrustResources = {
  en: { marketingTrust: {
    security: {
      title: 'Security', overview: 'EquipQR security controls and trust posture overview.', authTitle: 'Authentication and Access Control', authDescription: 'Identity, tenant isolation, and least-privilege access.', googleSignIn: 'Google Workspace OAuth is supported for sign-in and can inherit MFA enforcement at Google.', roleAccess: 'Organization and team access are role-based, with tenant isolation enforced through PostgreSQL RLS.', noAccess: 'New users have no effective team access until explicitly assigned.', dataTitle: 'Data Protection', dataTransit: 'Data is protected in transit with TLS and stored in managed Supabase/PostgreSQL infrastructure.', auditLogs: 'Audit logs are append-only and designed for traceability of critical data changes.', locationPrivacy: 'Organization-level privacy settings control optional collection of QR scan location data.', monitoringTitle: 'Monitoring and Response', securityEvents: 'Security-relevant events (member changes, role updates, audit exports) are available in notifications and audit history.', sessionControls: 'Session controls include inactivity timeout and support for global sign-out.', disclosureTitle: 'Responsible Disclosure', disclosureText: 'To report security concerns, contact',
    },
    repair: {
      stance: 'Public stance', title: 'Right to Repair', introduction: 'If you bought the machine, you should be able to keep it running. If you logged the work in EquipQR, that history is yours. We will not hold your data hostage.', commitments: 'What we commit to', exportTitle: 'Your records leave with you', exportBody: 'Organization owners can export operational data. If you stop using EquipQR, we do not keep your history locked behind a login as leverage.', noHostageTitle: 'We will not hold data hostage', noHostageBody: 'Subscription end is not a kill switch on the work you already logged. We do not design the product so your shop cannot read or take its own equipment history.', noPairingTitle: 'We do not lock the machines you service', noPairingBody: 'EquipQR is a records and work-order system. We do not pair replacement parts to our software, withhold diagnostics as a rent, or brick equipment from the cloud.',
    },
  } },
  vi: { marketingTrust: {
    security: {
      title: 'Bảo mật', overview: 'Tổng quan về các biện pháp bảo mật và độ tin cậy của EquipQR.', authTitle: 'Xác thực và kiểm soát truy cập', authDescription: 'Định danh, tách biệt dữ liệu tổ chức và quyền truy cập tối thiểu.', googleSignIn: 'Hỗ trợ đăng nhập bằng Google Workspace OAuth và có thể kế thừa yêu cầu MFA của Google.', roleAccess: 'Quyền truy cập tổ chức và đội dựa trên vai trò; dữ liệu các tổ chức được tách biệt bằng PostgreSQL RLS.', noAccess: 'Người dùng mới không có quyền truy cập đội cho đến khi được phân công rõ ràng.', dataTitle: 'Bảo vệ dữ liệu', dataTransit: 'Dữ liệu được bảo vệ khi truyền bằng TLS và lưu trong hạ tầng Supabase/PostgreSQL được quản lý.', auditLogs: 'Nhật ký kiểm toán chỉ cho phép thêm bản ghi và được thiết kế để truy vết các thay đổi dữ liệu quan trọng.', locationPrivacy: 'Cài đặt quyền riêng tư ở cấp tổ chức kiểm soát việc thu thập vị trí khi quét mã QR theo tùy chọn.', monitoringTitle: 'Giám sát và ứng phó', securityEvents: 'Các sự kiện liên quan đến bảo mật (thay đổi thành viên, cập nhật vai trò, xuất dữ liệu kiểm toán) có trong thông báo và lịch sử kiểm toán.', sessionControls: 'Kiểm soát phiên gồm thời gian chờ khi không hoạt động và hỗ trợ đăng xuất trên mọi thiết bị.', disclosureTitle: 'Thông báo vấn đề bảo mật', disclosureText: 'Để báo cáo vấn đề bảo mật, hãy liên hệ',
    },
    repair: {
      stance: 'Quan điểm công khai', title: 'Quyền sửa chữa', introduction: 'Nếu đã mua thiết bị, bạn có thể tiếp tục sử dụng và sửa chữa thiết bị đó. Lịch sử công việc bạn ghi trong EquipQR là của bạn. Chúng tôi sẽ không giữ dữ liệu của bạn làm công cụ ràng buộc.', commitments: 'Cam kết của chúng tôi', exportTitle: 'Bạn có thể mang theo hồ sơ của mình', exportBody: 'Chủ sở hữu tổ chức có thể xuất dữ liệu vận hành. Nếu ngừng dùng EquipQR, lịch sử của bạn sẽ không bị khóa sau màn hình đăng nhập để gây sức ép.', noHostageTitle: 'Chúng tôi không giữ dữ liệu làm công cụ ràng buộc', noHostageBody: 'Việc kết thúc gói đăng ký không xóa công việc bạn đã ghi. Chúng tôi không thiết kế sản phẩm khiến cửa hàng của bạn không thể đọc hoặc mang theo lịch sử thiết bị của mình.', noPairingTitle: 'Chúng tôi không khóa thiết bị bạn bảo trì', noPairingBody: 'EquipQR là hệ thống ghi chép và quản lý phiếu công việc. Chúng tôi không ghép cặp linh kiện thay thế với phần mềm, thu phí để giữ quyền chẩn đoán hoặc vô hiệu hóa thiết bị qua đám mây.',
    },
  } },
  ko: { marketingTrust: {
    security: {
      title: '보안', overview: 'EquipQR의 보안 제어와 신뢰성 개요입니다.', authTitle: '인증 및 접근 제어', authDescription: '신원 확인, 조직 데이터 격리, 최소 권한 접근입니다.', googleSignIn: 'Google Workspace OAuth 로그인을 지원하며 Google의 MFA 요구사항을 적용받을 수 있습니다.', roleAccess: '조직 및 팀 접근은 역할을 기반으로 하며 PostgreSQL RLS로 조직 간 데이터를 격리합니다.', noAccess: '새 사용자는 명시적으로 배정되기 전까지 팀 접근 권한이 없습니다.', dataTitle: '데이터 보호', dataTransit: '전송 중 데이터는 TLS로 보호하고 관리형 Supabase/PostgreSQL 인프라에 저장합니다.', auditLogs: '감사 로그는 추가만 가능하며 중요한 데이터 변경을 추적할 수 있도록 설계되었습니다.', locationPrivacy: '조직별 개인정보 설정에서 QR 스캔 위치 정보의 선택적 수집을 제어합니다.', monitoringTitle: '모니터링 및 대응', securityEvents: '보안 관련 이벤트(구성원 변경, 역할 업데이트, 감사 자료 내보내기)는 알림과 감사 기록에서 확인할 수 있습니다.', sessionControls: '세션 제어에는 비활동 시간 제한과 모든 기기에서 로그아웃하는 기능이 포함됩니다.', disclosureTitle: '보안 문제 제보', disclosureText: '보안 문제를 제보하려면 다음 주소로 연락하세요:',
    },
    repair: {
      stance: '공개 입장', title: '수리할 권리', introduction: '구매한 장비는 계속 사용할 수 있고 수리할 수 있어야 합니다. EquipQR에 기록한 작업 이력은 고객의 것입니다. 저희는 데이터를 이용해 고객을 묶어 두지 않습니다.', commitments: '저희의 약속', exportTitle: '기록을 가져갈 수 있습니다', exportBody: '조직 소유자는 운영 데이터를 내보낼 수 있습니다. EquipQR 사용을 중단해도 로그인 뒤에 이력을 가둬 고객을 붙잡지 않습니다.', noHostageTitle: '데이터를 볼모로 삼지 않습니다', noHostageBody: '구독이 끝나도 이미 기록한 작업을 읽을 수 없게 되지 않습니다. 작업장이 자체 장비 이력을 읽거나 가져갈 수 없게 만드는 제품을 설계하지 않습니다.', noPairingTitle: '정비하는 장비를 잠그지 않습니다', noPairingBody: 'EquipQR은 기록 및 작업 지시 시스템입니다. 교체 부품을 소프트웨어에 결합하거나 진단 기능을 유료로 제한하거나 클라우드를 통해 장비를 무력화하지 않습니다.',
    },
  } },
} as const;
