// Account notification, MFA, session, and security interface copy.
export const settingsSecurityResources = {
  en: { settingsSecurity: {
    submitted: 'Submitted', accepted: 'Accepted', assigned: 'Assigned', inProgress: 'In Progress', onHold: 'On Hold', completed: 'Completed', cancelled: 'Cancelled', enableTeam: 'Enable notifications for {{team}}', notifyWhen: 'Notify me when work orders are:', noTeams: "You're not a member of any teams yet", joinTeams: 'Join teams to configure notification preferences', teamsEnabled: '{{count}} teams enabled', howNotificationsWork: 'How notifications work', notificationsTeams: "You'll only receive notifications for teams you enable", notificationsStatuses: 'Choose which work order status changes trigger notifications', notificationsAdmins: 'Organization admins and owners can see all teams but can still customize preferences', notificationsRetention: 'Notifications appear in real-time and are kept for 30 days', roleOwner: 'Owner', roleAdmin: 'Admin', roleMember: 'Member',
    removeFailed: 'Failed to Remove', removeFailedHelp: 'Could not remove the authenticator. Please try again.', authenticatorRemoved: 'Authenticator Removed', mfaDisabled: 'Two-factor authentication has been disabled.', loadingMfa: 'Loading MFA status', mfaTitle: 'Two-Factor Authentication', enabled: 'Enabled', disabled: 'Disabled', mfaHelp: 'Add an extra layer of security to your account with a time-based one-time password (TOTP).', requiredForRole: 'Required for your role ({{role}}).', authenticatorApp: 'Authenticator App', addedDate: 'Added {{date}}', removeAuthenticator: 'Remove authenticator', removeAuthenticatorTitle: 'Remove Authenticator?', removeAuthenticatorHelp: 'This will disable two-factor authentication on your account. You will need to set it up again if you want to re-enable it.', cancel: 'Cancel', remove: 'Remove', mfaRequiredHelp: 'Two-factor authentication cannot be removed for admin and owner accounts.', setupMfa: 'Set Up Two-Factor Authentication',
    ownershipFirst: 'Organization ownership must be transferred first', pendingTransfer: 'Pending ownership transfer must be resolved', manualReviewRequired: 'Manual review is required before this account can be deleted', manualReviewBeforeDeletion: 'Manual review is required before deletion.', accountDeleted: 'Your EquipQR account has been deleted.', deleteFailed: 'Failed to delete account.', requestRecorded: 'Your deletion request was recorded. Our team will follow up if additional steps are needed.', requestFailed: 'Failed to submit deletion review request.', deleteAccount: 'Delete account', deleteConsequences: 'This permanently deletes your EquipQR login, personal settings, and avatar. Work you contributed to organizations — work orders, notes, photos, inventory, and audit history — stays with those organizations using your display name.', checkingDeletion: 'Checking whether your account can be deleted safely...', previewFailed: 'Preview failed.', retryPreview: 'Retry preview', confirmPhrase: 'Confirm by typing', verifyEmail: 'and verifying your account email', confirmationPhrase: 'Confirmation phrase', submitting: 'Submitting...', requestReview: 'Request manual review', deleting: 'Deleting...', deleteMyAccount: 'Delete my account',
    failed: 'Failed', passed: 'Passed', pending: 'Pending', securityStatus: 'Security Status', securityLoading: 'Loading security status...', securityRefresh: 'Refresh security status', organizationAccess: 'Organization Access', memberAccess: 'Member Access', teamAccess: 'Team Access', securityIssues: 'Security Issues:', securitySuccess: 'All security policies are working correctly. Database access is properly secured with RLS.',
    unknown: 'Unknown', signedOutAll: 'Signed out of all sessions', signOutFailed: 'Failed to sign out all sessions', sessionStatus: 'Session Status', sessionRefresh: 'Refresh session', sessionData: 'Session Data', loaded: 'Loaded', unavailable: 'Not Available', lastUpdated: 'Last Updated', lastSignIn: 'Last Sign In', organizations: 'Organizations', teamMemberships: 'Team Memberships', signOutAll: 'Sign out all sessions', signOutTitle: 'Sign out all active sessions?', signOutHelp: 'This revokes your active sessions across all devices. You will need to sign in again everywhere.', signOutEverywhere: 'Sign out everywhere', sessionSuccess: 'Session data loaded successfully. Using cached data for improved performance.',
  } },
  vi: { settingsSecurity: {
    submitted: 'Đã gửi', accepted: 'Đã tiếp nhận', assigned: 'Đã giao', inProgress: 'Đang thực hiện', onHold: 'Tạm dừng', completed: 'Hoàn thành', cancelled: 'Đã hủy', enableTeam: 'Bật thông báo cho {{team}}', notifyWhen: 'Thông báo khi phiếu công việc có trạng thái:', noTeams: 'Bạn chưa tham gia đội nào', joinTeams: 'Tham gia đội để tùy chỉnh thông báo', teamsEnabled: 'Đã bật {{count}} đội', howNotificationsWork: 'Cách hoạt động của thông báo', notificationsTeams: 'Bạn chỉ nhận thông báo từ các đội đã bật', notificationsStatuses: 'Chọn thay đổi trạng thái phiếu công việc sẽ gửi thông báo', notificationsAdmins: 'Quản trị viên và chủ sở hữu có thể xem mọi đội và tùy chỉnh thông báo', notificationsRetention: 'Thông báo xuất hiện theo thời gian thực và được giữ trong 30 ngày', roleOwner: 'Chủ sở hữu', roleAdmin: 'Quản trị viên', roleMember: 'Thành viên',
    removeFailed: 'Không thể gỡ', removeFailedHelp: 'Không thể gỡ ứng dụng xác thực. Vui lòng thử lại.', authenticatorRemoved: 'Đã gỡ ứng dụng xác thực', mfaDisabled: 'Đã tắt xác thực hai yếu tố.', loadingMfa: 'Đang tải trạng thái MFA', mfaTitle: 'Xác thực hai yếu tố', enabled: 'Đã bật', disabled: 'Đã tắt', mfaHelp: 'Tăng cường bảo mật tài khoản bằng mật khẩu dùng một lần theo thời gian (TOTP).', requiredForRole: 'Bắt buộc với vai trò của bạn ({{role}}).', authenticatorApp: 'Ứng dụng xác thực', addedDate: 'Thêm ngày {{date}}', removeAuthenticator: 'Gỡ ứng dụng xác thực', removeAuthenticatorTitle: 'Gỡ ứng dụng xác thực?', removeAuthenticatorHelp: 'Việc này sẽ tắt xác thực hai yếu tố trên tài khoản. Bạn phải thiết lập lại nếu muốn bật trở lại.', cancel: 'Hủy', remove: 'Gỡ', mfaRequiredHelp: 'Không thể gỡ xác thực hai yếu tố đối với tài khoản quản trị viên và chủ sở hữu.', setupMfa: 'Thiết lập xác thực hai yếu tố',
    ownershipFirst: 'Trước tiên phải chuyển quyền sở hữu tổ chức', pendingTransfer: 'Cần xử lý yêu cầu chuyển quyền sở hữu đang chờ', manualReviewRequired: 'Cần xem xét thủ công trước khi xóa tài khoản', manualReviewBeforeDeletion: 'Cần xem xét thủ công trước khi xóa.', accountDeleted: 'Tài khoản EquipQR của bạn đã được xóa.', deleteFailed: 'Không thể xóa tài khoản.', requestRecorded: 'Yêu cầu xóa tài khoản đã được ghi nhận. Chúng tôi sẽ liên hệ nếu cần thêm bước xử lý.', requestFailed: 'Không thể gửi yêu cầu xem xét xóa tài khoản.', deleteAccount: 'Xóa tài khoản', deleteConsequences: 'Việc này xóa vĩnh viễn tài khoản đăng nhập EquipQR, cài đặt cá nhân và ảnh đại diện. Công việc bạn đã đóng góp cho tổ chức — phiếu công việc, ghi chú, ảnh, tồn kho và lịch sử kiểm toán — vẫn thuộc về tổ chức và hiển thị tên của bạn.', checkingDeletion: 'Đang kiểm tra khả năng xóa tài khoản an toàn...', previewFailed: 'Không thể xem trước.', retryPreview: 'Thử xem trước lại', confirmPhrase: 'Xác nhận bằng cách nhập', verifyEmail: 'và kiểm tra email tài khoản', confirmationPhrase: 'Cụm từ xác nhận', submitting: 'Đang gửi...', requestReview: 'Yêu cầu xem xét thủ công', deleting: 'Đang xóa...', deleteMyAccount: 'Xóa tài khoản của tôi',
    failed: 'Thất bại', passed: 'Đạt', pending: 'Đang chờ', securityStatus: 'Trạng thái bảo mật', securityLoading: 'Đang tải trạng thái bảo mật...', securityRefresh: 'Làm mới trạng thái bảo mật', organizationAccess: 'Truy cập tổ chức', memberAccess: 'Truy cập thành viên', teamAccess: 'Truy cập đội', securityIssues: 'Vấn đề bảo mật:', securitySuccess: 'Các chính sách bảo mật đang hoạt động đúng. Quyền truy cập cơ sở dữ liệu được bảo vệ bằng RLS.',
    unknown: 'Không rõ', signedOutAll: 'Đã đăng xuất khỏi tất cả phiên', signOutFailed: 'Không thể đăng xuất khỏi tất cả phiên', sessionStatus: 'Trạng thái phiên', sessionRefresh: 'Làm mới phiên', sessionData: 'Dữ liệu phiên', loaded: 'Đã tải', unavailable: 'Không khả dụng', lastUpdated: 'Cập nhật gần nhất', lastSignIn: 'Đăng nhập gần nhất', organizations: 'Tổ chức', teamMemberships: 'Thành viên đội', signOutAll: 'Đăng xuất tất cả phiên', signOutTitle: 'Đăng xuất tất cả phiên đang hoạt động?', signOutHelp: 'Các phiên đang hoạt động trên mọi thiết bị sẽ bị thu hồi. Bạn cần đăng nhập lại ở tất cả thiết bị.', signOutEverywhere: 'Đăng xuất mọi nơi', sessionSuccess: 'Dữ liệu phiên đã tải thành công. Đang dùng dữ liệu lưu tạm để cải thiện tốc độ.',
  } },
  ko: { settingsSecurity: {
    submitted: '제출됨', accepted: '접수됨', assigned: '배정됨', inProgress: '진행 중', onHold: '보류', completed: '완료', cancelled: '취소됨', enableTeam: '{{team}} 알림 사용', notifyWhen: '작업 지시가 다음 상태일 때 알림:', noTeams: '아직 소속된 팀이 없습니다', joinTeams: '팀에 참여해 알림 설정을 구성하세요', teamsEnabled: '{{count}}개 팀 알림 사용', howNotificationsWork: '알림 작동 방식', notificationsTeams: '활성화한 팀의 알림만 받습니다', notificationsStatuses: '알림을 받을 작업 지시 상태 변경을 선택하세요', notificationsAdmins: '관리자와 소유자는 모든 팀을 볼 수 있으며 알림 설정을 맞춤화할 수 있습니다', notificationsRetention: '알림은 실시간으로 표시되며 30일 동안 보관됩니다', roleOwner: '소유자', roleAdmin: '관리자', roleMember: '구성원',
    removeFailed: '제거 실패', removeFailedHelp: '인증 앱을 제거할 수 없습니다. 다시 시도하세요.', authenticatorRemoved: '인증 앱 제거됨', mfaDisabled: '2단계 인증이 비활성화되었습니다.', loadingMfa: 'MFA 상태 불러오는 중', mfaTitle: '2단계 인증', enabled: '활성화', disabled: '비활성화', mfaHelp: '시간 기반 일회용 암호(TOTP)로 계정 보안을 강화하세요.', requiredForRole: '현재 역할({{role}})에 필수입니다.', authenticatorApp: '인증 앱', addedDate: '{{date}}에 추가됨', removeAuthenticator: '인증 앱 제거', removeAuthenticatorTitle: '인증 앱을 제거할까요?', removeAuthenticatorHelp: '계정의 2단계 인증이 꺼집니다. 다시 사용하려면 재설정해야 합니다.', cancel: '취소', remove: '제거', mfaRequiredHelp: '관리자와 소유자 계정에서는 2단계 인증을 제거할 수 없습니다.', setupMfa: '2단계 인증 설정',
    ownershipFirst: '먼저 조직 소유권을 이전해야 합니다', pendingTransfer: '대기 중인 소유권 이전을 해결해야 합니다', manualReviewRequired: '계정을 삭제하기 전에 수동 검토가 필요합니다', manualReviewBeforeDeletion: '삭제하기 전에 수동 검토가 필요합니다.', accountDeleted: 'EquipQR 계정이 삭제되었습니다.', deleteFailed: '계정을 삭제할 수 없습니다.', requestRecorded: '삭제 요청이 접수되었습니다. 추가 절차가 필요하면 담당자가 연락드리겠습니다.', requestFailed: '삭제 검토 요청을 제출할 수 없습니다.', deleteAccount: '계정 삭제', deleteConsequences: 'EquipQR 로그인, 개인 설정, 아바타가 영구적으로 삭제됩니다. 조직에 기여한 작업 지시, 메모, 사진, 재고 및 감사 기록은 표시 이름과 함께 해당 조직에 남습니다.', checkingDeletion: '안전하게 계정을 삭제할 수 있는지 확인하는 중...', previewFailed: '미리보기에 실패했습니다.', retryPreview: '미리보기 다시 시도', confirmPhrase: '확인 문구 입력:', verifyEmail: '및 계정 이메일 확인:', confirmationPhrase: '확인 문구', submitting: '제출하는 중...', requestReview: '수동 검토 요청', deleting: '삭제하는 중...', deleteMyAccount: '내 계정 삭제',
    failed: '실패', passed: '통과', pending: '대기', securityStatus: '보안 상태', securityLoading: '보안 상태를 불러오는 중...', securityRefresh: '보안 상태 새로고침', organizationAccess: '조직 접근', memberAccess: '구성원 접근', teamAccess: '팀 접근', securityIssues: '보안 문제:', securitySuccess: '모든 보안 정책이 정상적으로 작동합니다. 데이터베이스 접근은 RLS로 보호됩니다.',
    unknown: '알 수 없음', signedOutAll: '모든 세션에서 로그아웃했습니다', signOutFailed: '모든 세션에서 로그아웃할 수 없습니다', sessionStatus: '세션 상태', sessionRefresh: '세션 새로고침', sessionData: '세션 데이터', loaded: '로드됨', unavailable: '사용 불가', lastUpdated: '마지막 업데이트', lastSignIn: '마지막 로그인', organizations: '조직', teamMemberships: '팀 멤버십', signOutAll: '모든 세션에서 로그아웃', signOutTitle: '활성 세션에서 모두 로그아웃할까요?', signOutHelp: '모든 기기의 활성 세션이 철회됩니다. 모든 기기에서 다시 로그인해야 합니다.', signOutEverywhere: '모든 기기에서 로그아웃', sessionSuccess: '세션 데이터를 불러왔습니다. 성능 향상을 위해 캐시 데이터를 사용합니다.',
  } },
} as const;
