export const workOrderResources = {
  vi: {
    workOrders: {
      list: {
        title: 'Lệnh công việc', loading: 'Đang tải lệnh công việc theo nhóm...', pendingSync: 'Đang chờ đồng bộ', deleteAfterSync: 'Có thể xóa sau khi lệnh công việc đồng bộ xong.', noTeamAssignments: 'Bạn chưa được phân vào nhóm nào - hãy liên hệ quản trị viên để được cấp quyền', admin: 'Quản trị viên', team: '{{count}} nhóm', teams: '{{count}} nhóm', createWorkOrder: 'Tạo lệnh công việc', itemLabel: 'lệnh công việc', itemLabelPlural: 'lệnh công việc', createWorkOrderAria: 'Tạo lệnh công việc',
        searchPlaceholder: 'Tìm lệnh công việc...', searchAria: 'Tìm lệnh công việc', clearSearchAria: 'Xóa tìm kiếm', active: 'Đang áp dụng:', status: 'Trạng thái', assignee: 'Người được giao', priority: 'Ưu tiên', due: 'Hạn', dueDate: 'Ngày đến hạn', invoice: 'Hóa đơn', clearStatusFilterAria: 'Xóa bộ lọc trạng thái', clearAssigneeFilterAria: 'Xóa bộ lọc người được giao', clearPriorityFilterAria: 'Xóa bộ lọc ưu tiên', clearDueDateFilterAria: 'Xóa bộ lọc ngày đến hạn', clearInvoiceFilterAria: 'Xóa bộ lọc hóa đơn', clearAll: 'Xóa tất cả',
        filterAriaSubject: 'lệnh công việc', allAssignees: 'Tất cả người được giao', myWorkOrders: 'Lệnh công việc của tôi', mine: 'Của tôi', unassigned: 'Chưa giao', quickFilters: 'Bộ lọc nhanh', myWork: 'Công việc của tôi', urgent: 'Khẩn cấp', overdue: 'Quá hạn', myWorkTooltip: 'Chỉ hiển thị lệnh công việc được giao cho bạn', urgentTooltip: 'Chỉ hiển thị lệnh công việc ưu tiên cao', overdueTooltip: 'Chỉ hiển thị lệnh công việc đã quá ngày đến hạn', unassignedTooltip: 'Chỉ hiển thị lệnh công việc chưa được giao',
        filterByStatusAria: 'Lọc theo trạng thái', allStatuses: 'Tất cả trạng thái', filterByPriorityAria: 'Lọc theo mức ưu tiên', allPriorities: 'Tất cả mức ưu tiên', filterByDueDateAria: 'Lọc theo ngày đến hạn', allDates: 'Tất cả ngày', filterByInvoiceAria: 'Lọc theo trạng thái hóa đơn', allInvoices: 'Tất cả hóa đơn', submitted: 'Đã gửi', accepted: 'Đã chấp nhận', assigned: 'Đã giao', inProgress: 'Đang thực hiện', onHold: 'Tạm dừng', completed: 'Hoàn thành', cancelled: 'Đã hủy', high: 'Cao', medium: 'Trung bình', low: 'Thấp', dueToday: 'Đến hạn hôm nay', thisWeek: 'Tuần này', paid: 'Đã thanh toán', unpaid: 'Chưa thanh toán', notExported: 'Chưa xuất',
        sortAria: 'Sắp xếp lệnh công việc', sortCreatedNewest: 'Ngày tạo (mới nhất)', sortCreatedOldest: 'Ngày tạo (cũ nhất)', sortDueSoonest: 'Ngày đến hạn (sớm nhất)', sortDueLatest: 'Ngày đến hạn (muộn nhất)', sortPriorityHigh: 'Ưu tiên (cao trước)', sortPriorityLow: 'Ưu tiên (thấp trước)', sortStatusEarliest: 'Trạng thái (sớm trước)', sortStatusLatest: 'Trạng thái (muộn trước)',
        noWorkOrdersFound: 'Không tìm thấy lệnh công việc', noWorkAssigned: 'Hiện không có lệnh công việc nào được giao cho bạn.', noFilterMatches: 'Không có lệnh công việc nào khớp với bộ lọc hiện tại.', createFirst: 'Bắt đầu bằng cách tạo lệnh công việc đầu tiên.', calendarRange: 'Khoảng lịch', month: 'Tháng', week: 'Tuần', day: 'Ngày', viewAria: 'Chế độ xem lệnh công việc', listView: 'Dạng danh sách', calendarView: 'Dạng lịch', overview: 'Tổng quan lệnh công việc', addTime: 'Thêm giờ', unscheduled: 'Chưa lên lịch', equipment: 'Thiết bị', teamLabel: 'Nhóm', openDetails: 'Mở chi tiết',
      },
    },
  },
  en: {
    workOrders: {
      list: {
        title: 'Work Orders', loading: 'Loading team-based work orders...', pendingSync: 'Pending sync', deleteAfterSync: 'Delete is available after the work order syncs.', noTeamAssignments: 'No team assignments - contact your administrator for access', admin: 'Admin', team: '{{count}} team', teams: '{{count}} teams', createWorkOrder: 'Create Work Order', itemLabel: 'work order', itemLabelPlural: 'work orders', createWorkOrderAria: 'Create work order',
        searchPlaceholder: 'Search work orders...', searchAria: 'Search work orders', clearSearchAria: 'Clear search', active: 'Active:', status: 'Status', assignee: 'Assignee', priority: 'Priority', due: 'Due', dueDate: 'Due Date', invoice: 'Invoice', clearStatusFilterAria: 'Clear status filter', clearAssigneeFilterAria: 'Clear assignee filter', clearPriorityFilterAria: 'Clear priority filter', clearDueDateFilterAria: 'Clear due date filter', clearInvoiceFilterAria: 'Clear invoice filter', clearAll: 'Clear all',
        filterAriaSubject: 'work orders', allAssignees: 'All Assignees', myWorkOrders: 'My Work Orders', mine: 'Mine', unassigned: 'Unassigned', quickFilters: 'Quick filters', myWork: 'My Work', urgent: 'Urgent', overdue: 'Overdue', myWorkTooltip: 'Filter to work orders assigned to you', urgentTooltip: 'Filter to high-priority work orders', overdueTooltip: 'Filter to work orders past their due date', unassignedTooltip: 'Filter to unassigned work orders',
        filterByStatusAria: 'Filter by status', allStatuses: 'All Statuses', filterByPriorityAria: 'Filter by priority', allPriorities: 'All Priorities', filterByDueDateAria: 'Filter by due date', allDates: 'All Dates', filterByInvoiceAria: 'Filter by invoice status', allInvoices: 'All Invoices', submitted: 'Submitted', accepted: 'Accepted', assigned: 'Assigned', inProgress: 'In Progress', onHold: 'On Hold', completed: 'Completed', cancelled: 'Cancelled', high: 'High', medium: 'Medium', low: 'Low', dueToday: 'Due Today', thisWeek: 'This Week', paid: 'Paid', unpaid: 'Unpaid', notExported: 'Not Exported',
        sortAria: 'Sort work orders', sortCreatedNewest: 'Created (newest)', sortCreatedOldest: 'Created (oldest)', sortDueSoonest: 'Due Date (soonest)', sortDueLatest: 'Due Date (latest)', sortPriorityHigh: 'Priority (high first)', sortPriorityLow: 'Priority (low first)', sortStatusEarliest: 'Status (earliest)', sortStatusLatest: 'Status (latest)',
        noWorkOrdersFound: 'No work orders found', noWorkAssigned: 'No work orders are currently assigned to you.', noFilterMatches: 'No work orders match your current filters.', createFirst: 'Get started by creating your first work order.', calendarRange: 'Calendar range', month: 'Month', week: 'Week', day: 'Day', viewAria: 'Work orders view', listView: 'List view', calendarView: 'Calendar view', overview: 'Work order overview', addTime: 'Add time', unscheduled: 'Unscheduled', equipment: 'Equipment', teamLabel: 'Team', openDetails: 'Open details',
      },
    },
  },
  ko: {
    workOrders: {
      list: {
        title: '작업 지시', loading: '팀 기반 작업 지시를 불러오는 중...', pendingSync: '동기화 대기 중', deleteAfterSync: '작업 지시가 동기화된 후 삭제할 수 있습니다.', noTeamAssignments: '배정된 팀이 없습니다. 액세스 권한은 관리자에게 문의하세요.', admin: '관리자', team: '{{count}}개 팀', teams: '{{count}}개 팀', createWorkOrder: '작업 지시 만들기', itemLabel: '작업 지시', itemLabelPlural: '작업 지시', createWorkOrderAria: '작업 지시 만들기',
        searchPlaceholder: '작업 지시 검색...', searchAria: '작업 지시 검색', clearSearchAria: '검색 지우기', active: '적용 중:', status: '상태', assignee: '담당자', priority: '우선순위', due: '마감', dueDate: '마감일', invoice: '청구서', clearStatusFilterAria: '상태 필터 지우기', clearAssigneeFilterAria: '담당자 필터 지우기', clearPriorityFilterAria: '우선순위 필터 지우기', clearDueDateFilterAria: '마감일 필터 지우기', clearInvoiceFilterAria: '청구서 필터 지우기', clearAll: '모두 지우기',
        filterAriaSubject: '작업 지시', allAssignees: '모든 담당자', myWorkOrders: '내 작업 지시', mine: '내 담당', unassigned: '미배정', quickFilters: '빠른 필터', myWork: '내 작업', urgent: '긴급', overdue: '기한 초과', myWorkTooltip: '나에게 배정된 작업 지시만 표시', urgentTooltip: '우선순위가 높은 작업 지시만 표시', overdueTooltip: '마감일이 지난 작업 지시만 표시', unassignedTooltip: '미배정 작업 지시만 표시',
        filterByStatusAria: '상태별 필터', allStatuses: '모든 상태', filterByPriorityAria: '우선순위별 필터', allPriorities: '모든 우선순위', filterByDueDateAria: '마감일별 필터', allDates: '모든 날짜', filterByInvoiceAria: '청구서 상태별 필터', allInvoices: '모든 청구서', submitted: '제출됨', accepted: '수락됨', assigned: '배정됨', inProgress: '진행 중', onHold: '보류', completed: '완료', cancelled: '취소됨', high: '높음', medium: '보통', low: '낮음', dueToday: '오늘 마감', thisWeek: '이번 주', paid: '결제 완료', unpaid: '미결제', notExported: '미내보내기',
        sortAria: '작업 지시 정렬', sortCreatedNewest: '생성일 (최신순)', sortCreatedOldest: '생성일 (오래된 순)', sortDueSoonest: '마감일 (빠른 순)', sortDueLatest: '마감일 (늦은 순)', sortPriorityHigh: '우선순위 (높은 순)', sortPriorityLow: '우선순위 (낮은 순)', sortStatusEarliest: '상태 (이른 순)', sortStatusLatest: '상태 (늦은 순)',
        noWorkOrdersFound: '작업 지시를 찾을 수 없습니다', noWorkAssigned: '현재 나에게 배정된 작업 지시가 없습니다.', noFilterMatches: '현재 필터와 일치하는 작업 지시가 없습니다.', createFirst: '첫 작업 지시를 만들어 시작하세요.', calendarRange: '달력 범위', month: '월', week: '주', day: '일', viewAria: '작업 지시 보기', listView: '목록 보기', calendarView: '달력 보기', overview: '작업 지시 개요', addTime: '시간 추가', unscheduled: '일정 없음', equipment: '장비', teamLabel: '팀', openDetails: '세부 정보 열기',
      },
    },
  },
} as const;
