import { describe, expect, it, vi } from 'vitest';
import {
  createCanonicalDisplayImageRef,
  createMigrationImageSetId,
  isDisplayImageV2Ref,
  normalizeMigrationBatchLimit,
  resolveLegacyImageSource,
  runLegacyDisplayImageMigration,
  type DisplayImageVariantBytes,
  type LegacyDisplayImageCandidate,
  type MigrationDatabase,
  type MigrationStorage,
} from './migrate-legacy-display-images-core';

function makeCandidate(
  overrides: Partial<LegacyDisplayImageCandidate> = {},
): LegacyDisplayImageCandidate {
  return {
    id: 'row-1',
    entity: 'inventory',
    organizationId: 'org-1',
    entityId: 'item-1',
    storedRef: 'inventory-item-images/org-1/item-1/photo.jpg',
    table: 'inventory_item_images',
    fileName: 'photo.jpg',
    fileSize: 4,
    mimeType: 'image/jpeg',
    ...overrides,
  };
}

function makeVariants(): DisplayImageVariantBytes {
  return {
    thumb: Uint8Array.of(1),
    preview: Uint8Array.of(2, 3),
    full: Uint8Array.of(4, 5, 6),
  };
}

function makeDatabase(
  rows: LegacyDisplayImageCandidate[],
): MigrationDatabase & {
  listCandidates: ReturnType<typeof vi.fn>;
  updateCanonicalRef: ReturnType<typeof vi.fn>;
} {
  return {
    listCandidates: vi.fn(async () => ({
      rows,
      nextCursor: 'next-cursor',
    })),
    updateCanonicalRef: vi.fn(async () => true),
  };
}

function makeStorage(): MigrationStorage & {
  download: ReturnType<typeof vi.fn>;
  upload: ReturnType<typeof vi.fn>;
  stat: ReturnType<typeof vi.fn>;
} {
  return {
    download: vi.fn(async () => ({
      bytes: Uint8Array.of(9, 8, 7, 6),
      contentType: 'image/jpeg',
    })),
    upload: vi.fn(async () => 'uploaded' as const),
    remove: vi.fn(async () => undefined),
    stat: vi.fn(async () => ({ exists: true })),
  };
}

describe('legacy display-image migration core', () => {
  it('keeps dry-run read-only while reporting generated byte totals', async () => {
    const database = makeDatabase([
      makeCandidate({
        id: 'v2-row',
        storedRef:
          'display-images/org/org-1/inventory/item-1/image-set/full.webp',
      }),
      makeCandidate(),
    ]);
    const storage = makeStorage();
    const convertToVariants = vi.fn(async () => makeVariants());

    const report = await runLegacyDisplayImageMigration(
      { database, storage, convertToVariants },
      {
        mode: 'dry-run',
        limit: 25,
        cursor: null,
        entity: 'all',
      },
    );

    expect(report.scanned).toBe(2);
    expect(report.skipped).toBe(1);
    expect(report.wouldMigrate).toBe(1);
    expect(report.migrated).toBe(0);
    expect(report.failed).toBe(0);
    expect(report.bytesBefore).toBe(4);
    expect(report.bytesAfter).toBe(6);
    expect(storage.upload).not.toHaveBeenCalled();
    expect(storage.stat).not.toHaveBeenCalled();
    expect(database.updateCanonicalRef).not.toHaveBeenCalled();
  });

  it('uploads and verifies all variants before the guarded DB update', async () => {
    const candidate = makeCandidate({
      id: 'equipment-row',
      entity: 'equipment',
      organizationId: 'org-1',
      entityId: 'equipment-1',
      storedRef:
        'https://example.supabase.co/storage/v1/object/public/work-order-images/user-1/work-order-1/photo.jpg',
      table: 'equipment',
    });
    const database = makeDatabase([candidate]);
    const storage = makeStorage();
    const events: string[] = [];
    storage.upload.mockImplementation(async () => {
      events.push('upload');
      return 'uploaded';
    });
    storage.stat.mockImplementation(async () => {
      events.push('stat');
      return { exists: true };
    });
    database.updateCanonicalRef.mockImplementation(async () => {
      events.push('update');
      return true;
    });

    const report = await runLegacyDisplayImageMigration(
      {
        database,
        storage,
        convertToVariants: async () => makeVariants(),
      },
      {
        mode: 'apply',
        limit: 1,
        cursor: null,
        entity: 'equipment',
      },
    );

    expect(report.migrated).toBe(1);
    expect(report.failed).toBe(0);
    expect(storage.upload).toHaveBeenCalledTimes(3);
    expect(storage.upload.mock.calls.map((call) => call[1])).toEqual([
      'org/org-1/equipment/equipment-1/be9a375d-36a7-45f2-953e-32b7d3a58de7/thumb.webp',
      'org/org-1/equipment/equipment-1/be9a375d-36a7-45f2-953e-32b7d3a58de7/preview.webp',
      'org/org-1/equipment/equipment-1/be9a375d-36a7-45f2-953e-32b7d3a58de7/full.webp',
    ]);
    expect(database.updateCanonicalRef).toHaveBeenCalledWith(
      candidate,
      'display-images/org/org-1/equipment/equipment-1/be9a375d-36a7-45f2-953e-32b7d3a58de7/full.webp',
    );
    expect(events.at(-1)).toBe('update');
  });

  it('does not abort the batch when one row fails', async () => {
    const database = makeDatabase([
      makeCandidate({ id: 'bad-row' }),
      makeCandidate({
        id: 'good-row',
        entityId: 'item-2',
        storedRef: 'inventory-item-images/org-1/item-2/photo.png',
      }),
    ]);
    const storage = makeStorage();
    const convertToVariants = vi
      .fn()
      .mockRejectedValueOnce(new Error('decode failed'))
      .mockResolvedValueOnce(makeVariants());

    const report = await runLegacyDisplayImageMigration(
      { database, storage, convertToVariants },
      {
        mode: 'apply',
        limit: 2,
        cursor: 'start-cursor',
        entity: 'inventory',
      },
    );

    expect(report.failed).toBe(1);
    expect(report.migrated).toBe(1);
    expect(report.failures[0]).toMatchObject({
      id: 'bad-row',
      entity: 'inventory',
      reason: 'decode failed',
    });
    expect(report.resumeCursor).toBe('start-cursor');
    expect(database.updateCanonicalRef).toHaveBeenCalledTimes(1);
  });

  it('cleans newly uploaded variants when the guarded DB update fails', async () => {
    const candidate = makeCandidate();
    const database = makeDatabase([candidate]);
    database.updateCanonicalRef.mockResolvedValueOnce(false);
    const storage = makeStorage();

    const report = await runLegacyDisplayImageMigration(
      {
        database,
        storage,
        convertToVariants: async () => makeVariants(),
      },
      {
        mode: 'apply',
        limit: 1,
        cursor: null,
        entity: 'inventory',
      },
    );

    expect(report.failed).toBe(1);
    expect(report.migrated).toBe(0);
    expect(storage.remove).toHaveBeenCalledWith(
      'display-images',
      expect.arrayContaining([
        expect.stringContaining('/thumb.webp'),
        expect.stringContaining('/preview.webp'),
        expect.stringContaining('/full.webp'),
      ]),
    );
    expect(storage.remove.mock.calls[0]?.[1]).toHaveLength(3);
  });

  it('does not remove pre-existing retry objects when a later upload fails', async () => {
    const candidate = makeCandidate();
    const database = makeDatabase([candidate]);
    const storage = makeStorage();
    storage.upload
      .mockResolvedValueOnce('already-exists')
      .mockResolvedValueOnce('uploaded')
      .mockRejectedValueOnce(new Error('full upload failed'));

    const report = await runLegacyDisplayImageMigration(
      {
        database,
        storage,
        convertToVariants: async () => makeVariants(),
      },
      {
        mode: 'apply',
        limit: 1,
        cursor: null,
        entity: 'inventory',
      },
    );

    expect(report.failed).toBe(1);
    expect(storage.remove).toHaveBeenCalledWith(
      'display-images',
      [expect.stringContaining('/preview.webp')],
    );
  });

  it('recognizes V2 refs and parses safe legacy bucket paths', () => {
    expect(
      isDisplayImageV2Ref(
        'https://example.supabase.co/storage/v1/object/public/display-images/org/org-1/inventory/item-1/set-1/thumb.webp',
      ),
    ).toBe(true);

    expect(
      resolveLegacyImageSource(
        makeCandidate({
          storedRef:
            'https://example.supabase.co/storage/v1/object/sign/inventory-item-images/org-1/item-1/photo.jpg?token=secret',
        }),
      ),
    ).toEqual({
      source: {
        bucket: 'inventory-item-images',
        path: 'org-1/item-1/photo.jpg',
      },
    });

    expect(
      resolveLegacyImageSource(
        makeCandidate({
          entity: 'equipment',
          entityId: 'equipment-1',
          table: 'equipment',
          storedRef: 'user-1/equipment-1/note-1/photo.jpg',
        }),
      ),
    ).toEqual({
      source: {
        bucket: 'equipment-note-images',
        path: 'user-1/equipment-1/note-1/photo.jpg',
      },
    });

    expect(
      resolveLegacyImageSource(
        makeCandidate({
          storedRef: 'https://images.example.com/photo.jpg',
        }),
      ),
    ).toEqual({ skipReason: 'unsupported external image URL' });
  });

  it('derives a UUID-shaped deterministic set id and keeps limits bounded', () => {
    const id = createMigrationImageSetId(makeCandidate());
    expect(id).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
    );
    expect(normalizeMigrationBatchLimit(0)).toBe(1);
    expect(normalizeMigrationBatchLimit(1000)).toBe(100);
    expect(
      createCanonicalDisplayImageRef({
        organizationId: 'org-1',
        entity: 'inventory',
        entityId: 'item-1',
        imageSetId: id,
      }),
    ).toBe('display-images/org/org-1/inventory/item-1/' + id + '/full.webp');
  });
});
