import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { FormControl, FormField, FormItem, FormLabel, FormMessage, FormDescription } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { AutocompleteInput } from "@/components/ui/autocomplete-input";
import { UseFormReturn } from 'react-hook-form';
import { useOrganization } from '@/contexts/OrganizationContext';
import { useEquipmentManufacturersAndModels } from '@/features/equipment/hooks/useEquipment';
import { type EquipmentFormData, generateEquipmentName } from '@/features/equipment/types/equipment';
import { useManufacturerModelSuggestions } from '@/features/equipment/utils/manufacturerModelLookup';
import type { DuplicateEquipmentMatch } from '@/features/equipment/services/EquipmentService';
import { DuplicateSerialWarning } from '@/features/equipment/components/DuplicateSerialWarning';
import { useI18n } from '@/i18n';

interface EquipmentBasicInfoSectionProps {
  form: UseFormReturn<EquipmentFormData>;
  duplicateMatch?: DuplicateEquipmentMatch | null;
  onDuplicateNavigate?: () => void;
}

const EquipmentBasicInfoSection: React.FC<EquipmentBasicInfoSectionProps> = ({
  form,
  duplicateMatch,
  onDuplicateNavigate,
}) => {
  const { t } = useI18n();
  const { currentOrganization } = useOrganization();
  const { data: manufacturersData = [] } = useEquipmentManufacturersAndModels(currentOrganization?.id);
  const [nameManuallyEdited, setNameManuallyEdited] = useState(false);
  const manufacturer = form.watch('manufacturer');
  const model = form.watch('model');
  const name = form.watch('name');

  const isEdit = useMemo(() => !!form.formState.defaultValues?.name, [form.formState.defaultValues?.name]);

  useEffect(() => {
    if (!nameManuallyEdited && !isEdit) {
      const generatedName = generateEquipmentName(manufacturer || '', model || '');
      if (generatedName && generatedName !== name) form.setValue('name', generatedName);
    }
  }, [manufacturer, model, nameManuallyEdited, isEdit, form, name]);

  const { manufacturers, modelsForManufacturer } = useManufacturerModelSuggestions(manufacturersData, manufacturer);

  const handleNameChange = useCallback((e: React.ChangeEvent<HTMLInputElement>, fieldOnChange: (value: string) => void) => {
    setNameManuallyEdited(true);
    fieldOnChange(e.target.value);
  }, []);

  return (
    <Card>
      <CardContent className="pt-4 space-y-4">
        <h3 className="font-medium text-sm text-muted-foreground uppercase tracking-wide">{t('equipmentForm.basicInformation')}</h3>
        <FormField control={form.control} name="manufacturer" render={({ field }) => (
          <FormItem>
            <FormLabel>{t('equipmentForm.manufacturerRequired')}</FormLabel>
            <FormControl>
              <AutocompleteInput
                placeholder={t('equipmentForm.manufacturerPlaceholder')}
                suggestions={manufacturers}
                value={field.value || ''}
                onChange={(value) => {
                  field.onChange(value);
                  if (!value) setNameManuallyEdited(false);
                }}
                emptyMessage={t('equipmentForm.noMatchingManufacturers')}
              />
            </FormControl>
            {manufacturers.length > 0 && !manufacturer && (
              <FormDescription>{t('equipmentForm.manufacturerSuggestions', { count: manufacturers.length })}</FormDescription>
            )}
            <FormMessage />
          </FormItem>
        )} />
        <FormField control={form.control} name="model" render={({ field }) => (
          <FormItem>
            <FormLabel>{t('equipmentForm.modelRequired')}</FormLabel>
            <FormControl>
              <AutocompleteInput
                placeholder={t('equipmentForm.modelPlaceholder')}
                suggestions={modelsForManufacturer}
                value={field.value || ''}
                onChange={(value) => {
                  field.onChange(value);
                  if (!value) setNameManuallyEdited(false);
                }}
                emptyMessage={t('equipmentForm.noMatchingModels')}
              />
            </FormControl>
            {modelsForManufacturer.length > 0 && !model && (
              <FormDescription>{t('equipmentForm.modelSuggestions', { count: modelsForManufacturer.length, manufacturer: manufacturer || '' })}</FormDescription>
            )}
            <FormMessage />
          </FormItem>
        )} />
        <FormField control={form.control} name="name" render={({ field }) => (
          <FormItem>
            <FormLabel>
              {t('equipmentForm.equipmentNameRequired')}
              {!isEdit && !nameManuallyEdited && name && (
                <span className="text-muted-foreground ml-1 font-normal">{t('equipmentForm.autoGenerated')}</span>
              )}
            </FormLabel>
            <FormControl>
              <Input placeholder={t('equipmentForm.equipmentNamePlaceholder')} {...field} onChange={(e) => handleNameChange(e, field.onChange)} />
            </FormControl>
            {!isEdit && <FormDescription>{t('equipmentForm.equipmentNameDescription')}</FormDescription>}
            <FormMessage />
          </FormItem>
        )} />
        <FormField control={form.control} name="serial_number" render={({ field }) => (
          <FormItem>
            <FormLabel>
              {t('equipmentForm.serialNumberRequired').replace(/\s*\*$/, '')}
              <span className="font-normal text-muted-foreground"> (optional)</span>
            </FormLabel>
            <FormControl><Input placeholder={t('equipmentForm.serialNumberPlaceholder')} {...field} /></FormControl>
            <FormDescription>Leave blank when the asset has no manufacturer serial number or it is no longer readable.</FormDescription>
            <FormMessage />
            {duplicateMatch && <DuplicateSerialWarning match={duplicateMatch} inline onNavigate={onDuplicateNavigate} />}
          </FormItem>
        )} />
      </CardContent>
    </Card>
  );
};

export default EquipmentBasicInfoSection;
