import { describe, expect, it } from 'vitest';
import { generateSeedFiles } from './generate-seeds';
import { SeededRng } from './rng';
import { deterministicUuid, escapeSql } from './sql-builder';
import { ORGS, UUID_PREFIXES } from './reference-data';

const APEX_ORG_ID = ORGS.apex.id;
const APEX_TECHNICIAN_ID = 'bb0e8400-e29b-41d4-a716-446655440003';

describe('generateSeedFiles', () => {
  it('is deterministic — two runs at the same scale emit identical SQL', () => {
    const first = generateSeedFiles(1);
    const second = generateSeedFiles(1);

    expect(first.files.map((f) => f.fileName)).toEqual(second.files.map((f) => f.fileName));
    for (let i = 0; i < first.files.length; i++) {
      expect(first.files[i].sql).toBe(second.files[i].sql);
    }
  });

  it('scales volume linearly with the --scale knob', () => {
    const base = generateSeedFiles(1).summary;
    const doubled = generateSeedFiles(2).summary;

    expect(base['inventory.items']).toBe(900);
    expect(doubled['inventory.items']).toBe(1800);
    expect(doubled['equipment.equipment']).toBe(base['equipment.equipment'] * 2);
    expect(doubled['workOrders.workOrders']).toBe(base['workOrders.workOrders'] * 2);
    expect(doubled['operatorCheckins.submissions']).toBe(base['operatorCheckins.submissions'] * 2);
    // Durable RBAC grants stay fixed regardless of scale.
    expect(doubled['partsRbac.partsManagers']).toBe(base['partsRbac.partsManagers']);
  });

  it('rejects non-integer or out-of-range scales', () => {
    expect(() => generateSeedFiles(0)).toThrow(/--scale/);
    expect(() => generateSeedFiles(1.5)).toThrow(/--scale/);
    expect(() => generateSeedFiles(101)).toThrow(/--scale/);
  });

  it('covers every generated domain with non-empty INSERTs', () => {
    const { files, summary } = generateSeedFiles(1);

    const byName = Object.fromEntries(files.map((f) => [f.fileName, f.sql]));
    expect(byName['50_generated_equipment.sql']).toContain('INSERT INTO public.equipment');
    expect(byName['51_generated_inventory.sql']).toContain('INSERT INTO public.inventory_items');
    expect(byName['51_generated_inventory.sql']).toContain('INSERT INTO public.part_alternate_groups');
    expect(byName['52_generated_work_orders.sql']).toContain('INSERT INTO public.work_orders');
    expect(byName['52_generated_work_orders.sql']).toContain('INSERT INTO public.work_order_costs');
    expect(byName['52_generated_work_orders.sql']).toContain('INSERT INTO public.inventory_transactions');
    expect(byName['53_generated_parts_rbac.sql']).toContain('INSERT INTO public.parts_managers');
    expect(byName['53_generated_parts_rbac.sql']).toContain('INSERT INTO public.parts_consumers');
    expect(byName['54_generated_operator_checkins.sql']).toContain(
      'INSERT INTO public.operator_checklist_templates',
    );
    expect(byName['54_generated_operator_checkins.sql']).toContain(
      'INSERT INTO public.operator_checkin_submissions',
    );

    expect(summary['workOrders.costs']).toBeGreaterThan(0);
    expect(summary['workOrders.transactions']).toBeGreaterThan(0);
  });

  it('never grants Apex members inventory RBAC (E2E deny-path guardrail)', () => {
    const { files } = generateSeedFiles(1);
    const rbacSql = files.find((f) => f.fileName === '53_generated_parts_rbac.sql')!.sql;

    expect(rbacSql).not.toContain(APEX_ORG_ID);
    expect(rbacSql).not.toContain(APEX_TECHNICIAN_ID);
  });

  it('keeps Apex operator check-ins empty (evidence spec resets Apex from clean slate)', () => {
    const { files } = generateSeedFiles(1);
    const checkinSql = files.find((f) => f.fileName === '54_generated_operator_checkins.sql')!.sql;

    expect(checkinSql).not.toContain(APEX_ORG_ID);
    expect(checkinSql).toContain(ORGS.metro.id);
  });

  it('marks every generated file as auto-generated with idempotent inserts', () => {
    const { files } = generateSeedFiles(1);
    for (const file of files) {
      expect(file.sql).toContain('AUTO-GENERATED by dev/seed-data/generate-seeds.ts');
      expect(file.sql).toContain('ON CONFLICT');
    }
  });
});

describe('sql-builder helpers', () => {
  it('deterministicUuid pads counters and validates inputs', () => {
    expect(deterministicUuid('d10e8400', 7)).toBe('d10e8400-e29b-41d4-a716-446655000007');
    expect(() => deterministicUuid('nothex!!', 1)).toThrow(/prefix/);
    expect(() => deterministicUuid('d10e8400', 1000000)).toThrow(/counter/);
  });

  it('escapeSql doubles single quotes and handles NULL', () => {
    expect(escapeSql("O'Reilly")).toBe("'O''Reilly'");
    expect(escapeSql(null)).toBe('NULL');
  });

  it('generated UUID prefixes stay disjoint from durable-core prefixes', () => {
    const reserved = ['aa0e8400', 'a00e8400', 'a10e8400', 'a20e8400', 'a30e8400', 'bb0e8400', '660e8400', '880e8400', 'cc0e8400', 'b00e8400', 'f00e8400'];
    for (const prefix of Object.values(UUID_PREFIXES)) {
      expect(reserved).not.toContain(prefix);
    }
  });
});

describe('SeededRng', () => {
  it('never returns 1.0 and int() stays within bounds', () => {
    const rng = new SeededRng(1164);
    for (let i = 0; i < 2_000; i++) {
      const value = rng.next();
      expect(value).toBeGreaterThanOrEqual(0);
      expect(value).toBeLessThan(1);
      const picked = rng.int(3, 9);
      expect(picked).toBeGreaterThanOrEqual(3);
      expect(picked).toBeLessThanOrEqual(9);
    }
  });
});
