/**
 * SQL emission helpers shared by all seed-data generators.
 *
 * Generated files are written to supabase/seeds/generated/ (gitignored) and
 * applied by `supabase db reset` after the committed durable-core seeds.
 */

export function escapeSql(value: string | null): string {
  if (value === null) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

export function uuidLiteral(value: string | null): string {
  return value === null ? 'NULL' : `'${value}'::uuid`;
}

export function jsonbLiteral(value: unknown): string {
  return `${escapeSql(JSON.stringify(value))}::jsonb`;
}

/**
 * Deterministic UUID from an 8-hex-char prefix and a numeric counter.
 * Example: deterministicUuid('d10e8400', 12) -> 'd10e8400-e29b-41d4-a716-446655000012'
 */
export function deterministicUuid(prefix: string, counter: number): string {
  if (!/^[0-9a-f]{8}$/.test(prefix)) {
    throw new Error(`Invalid UUID prefix "${prefix}" (expected 8 lowercase hex chars)`);
  }
  if (!Number.isInteger(counter) || counter < 0 || counter > 999999) {
    throw new Error(`UUID counter out of range: ${counter}`);
  }
  return `${prefix}-e29b-41d4-a716-446655${counter.toString().padStart(6, '0')}`;
}

export interface SeedFileSection {
  title: string;
  insert: {
    table: string;
    columns: string[];
    /** Each entry is the parenthesized tuple body (without trailing comma). */
    rows: string[];
    conflictClause?: string;
  };
}

/** Render a full seed SQL file with a standard header and INSERT sections. */
export function renderSeedFile(options: {
  fileTitle: string;
  descriptionLines: string[];
  sections: SeedFileSection[];
}): string {
  const lines: string[] = [];
  const bar = '-- =====================================================';

  lines.push(bar);
  lines.push(`-- ${options.fileTitle}`);
  lines.push(bar);
  lines.push('-- AUTO-GENERATED by dev/seed-data/generate-seeds.ts — DO NOT EDIT.');
  lines.push('-- Regenerate with: npm run seed:generate');
  for (const desc of options.descriptionLines) {
    lines.push(`-- ${desc}`);
  }
  lines.push('');

  for (const section of options.sections) {
    if (section.insert.rows.length === 0) continue;
    lines.push(bar);
    lines.push(`-- ${section.title} (${section.insert.rows.length} rows)`);
    lines.push(bar);
    lines.push(`INSERT INTO ${section.insert.table} (`);
    lines.push(`  ${section.insert.columns.join(', ')}`);
    lines.push(') VALUES');
    lines.push(section.insert.rows.map((row) => `  (${row})`).join(',\n'));
    lines.push(`${section.insert.conflictClause ?? 'ON CONFLICT (id) DO NOTHING'};`);
    lines.push('');
  }

  return lines.join('\n');
}
