-- Migration: remote_schema
-- This migration was previously applied to the database and then the file was deleted.
-- This is a placeholder file to sync local migrations with the remote database state.
-- The actual schema changes from this migration are already present in the database.
--
-- DO NOT modify this file - it exists only to match production state and prevent
-- "Remote migration versions not found in local migrations directory" errors.
--
-- Production application reference:
--   - Migration version: 20251227181824 (from this file's timestamped filename)
--   - Reflects the remote/production schema state as of 2025-12-27T18:18:24Z
--   - Original migration was generated via Supabase remote schema pull and contained
--     function definitions and schema changes that are now part of the base schema.
--   - See deployment logs and docs/ops/migration-rules-quick-reference.md for details.
--
-- Local development compatibility:
--   - This placeholder is safe for local development environments
--   - Running `npx supabase db reset` will apply this migration as a no-op
--   - The SELECT 1 statement ensures the migration completes successfully without errors
--   - Local environments that haven't applied this migration will apply it as a no-op

-- No-op: migration already applied
SELECT 1;
