-- CONSOLIDATED: This migration's logic was folded into
-- 20260201000000_allow_org_admin_assignee_when_equipment_has_no_team.sql
-- so the cross-tenant guard is never absent between migration versions.
--
-- This stub file exists only to satisfy Supabase CLI migration version
-- tracking; it intentionally performs no schema changes.
