export const DEFAULT_INVENTORY_DESKTOP_PAGE_SIZE = 25;
export const DEFAULT_INVENTORY_MOBILE_PAGE_SIZE = 12;

export const INVENTORY_DESKTOP_PAGE_SIZE_OPTIONS = [25, 50, 100, 200] as const;
export const INVENTORY_MOBILE_PAGE_SIZE_OPTIONS = [12, 24, 36, 48] as const;
